### ISSUE TITLE
Causes Server Crash

### ISSUE THREAD

**Issue by judicius** [architectury/architectury#102]
MC 1.16.5
Forge 36.1.24
Architectury 1.17.20

Server crashes and will not start.

https://gist.github.com/judicius/3d2a92a7b889c689dd6b2fd99f7486bf

**Comment by judicius** [comment]
this was a false report of another issue, sorry for the inconvenience.

**Comment by MaxNeedsSnacks** [comment]
No worries! This seems to be race condition that happens seemingly at random, we’ll probably have to look into it for 1.17 at the very least
