### ISSUE TITLE
Source code jars in maven

### ISSUE THREAD

**Issue by warjort** [architectury/architectury#103]
The source code for architecury-api uploaded to maven has a -dev classifier which I think is what is stopping it getting downloaded when you run the gensources task?

FYI: Cloth config has the same issue, but REI looks to be doing right.

**Comment by shedaniel** [comment]
This repo is currently based on a broken version of the example mod with no working sources artefact and remapping.

REI is not, I will fix this soon for both architectury api and cloth config.

**Comment by warjort** [comment]
Thanks for fixing this.
