### ISSUE TITLE
Crash mouseClicked event handler  java.lang.NoClassDefFoundError: me/shedaniel/clothconfig2/api/AbstractConfigListEntry

### ISSUE THREAD

**Issue by PrangellPlays** [architectury/architectury#107]
[crash-2021-06-10_16.41.17-client.txt](https://github.com/architectury/architectury-api/files/6632840/crash-2021-06-10_16.41.17-client.txt)

**Comment by MaxNeedsSnacks** [comment]
This isn't related to Architectury, please report this to the author of NetheritePlus
