### ISSUE TITLE
[Request] Client Commands API

### ISSUE THREAD

**Issue by BasiqueEvangelist** [architectury/architectury#121]
**Forge**: No equivalent right now. There is an open PR adding client commands (MinecraftForge/MinecraftForge#7754)
**Fabric**: [`ClientCommandManager`](https://github.com/FabricMC/fabric/blob/1.16/fabric-command-api-v1/src/main/java/net/fabricmc/fabric/api/client/command/v1/ClientCommandManager.java)

**Comment by SiongSng** [comment]
Now https://github.com/MinecraftForge/MinecraftForge/pull/7754 has been merged
