### ISSUE TITLE
Initializing shaders crash with requiem 2.0.0-alpha.6

### ISSUE THREAD

**Issue by ghost** [architectury/architectury#123]
Crashlog provided on discord, https://gist.github.com/NinjaPhenix/47f5f35c33b97f6af0094cea8b2ade0f

**Comment by Pyrofab** [comment]
Sorry about that, it's my fault. Architectury had an old crash with satin that I fixed recently, but I didn't realize the Architectury team fixed it first. And when both fixes are active, nothing gets fixed... I'll just remove it Satin side, no need to do anything.

**Comment by ghost** [comment]
Thanks, will let shedaniel know ( if they haven't already seen this ofc )
