### ISSUE TITLE
[1.12.2] mod

### ISSUE THREAD

**Issue by DoctorCheese1** [architectury/architectury#126]
when can you make a 1.12.2 supported mod?

**Comment by Username404-59** [comment]
Uh why would you want to make a mod that uses architectury on 1.12.2 if fabric exists for 1.14+ only?

Also why do you want to play on minecraft 1.12.2 in the first place, 1.16 and 1.17 are the latest versions

**Comment by wagyourtail** [comment]
https://legacyfabric.net/

**Comment by DoctorCheese1** [comment]
i need it for forge

**Comment by Leo40Git** [comment]
Architectury only supports 1.15 and up, with 1.16 and 1.17 being the currently active versions (AFAIK).

Backporting is extremely unlikely, especially considering Fabric is pretty much nonexistent (officially) on earlier versions.

**Comment by Username404-59** [comment]
wagyourtail I meant the official fabric, not a fork

**Comment by wagyourtail** [comment]
yeah. well legacyfabric is the only one and is as "official" as it gets for <1.14, their quality and dedication is on par with fabric. 
As for actually making arch-api for older versions, it's not worth the time to support older minecraft versions anyway.

**Comment by shedaniel** [comment]
We support 1.14+ with the current toolchain, and has no concrete plans to support the more legacy versions, Architectury Loom for 1.12 might happen, but the various Forge Gradle forks may get you that anyways. Legacy Fabric is incomplete and has severe problems (Sorry people from there I know I abandoned you all), and isn't on the list of viable mod loaders to support, so developing multiple mod loaders for versions before 1.14 is pointless.
