### ISSUE TITLE
Crash with Mod Menu

### ISSUE THREAD

**Issue by maicol07** [architectury/architectury#127]
Crash when I type a character in the mod menu search bar.

Crash report: [bytebin.lucko.me/9lzLNmrMLI](https://bytebin.lucko.me/9lzLNmrMLI)

**Comment by OakBricks-old** [comment]
this is an issue for the guys at modmenu https://github.com/TerraformersMC/ModMenu

**Comment by shedaniel** [comment]
Unrelated to architectury, please report to ModMenu as suggested above.
