### ISSUE TITLE
Launching problem - server side

### ISSUE THREAD

**Issue by Nefasxcc1** [architectury/architectury#130]
Architectury (architectury) has failed to load correctly is the message i get while trying to launch forge server, running Architectury.
Same problem while using forge 36.2.0 | 36.1.65 | 36.1.32 | 36.1.25, didn't try others, as i found it pointless.
Obviously i tried older versions of Architectury, but still, same problem.
Client side works perfectly fine.
I'm using version Mods Version 1.16.5, with Forge 36.2.0, but tried older versions as well.

> [CSRV] Changing working dir...
> [CSRV] Scanning for network conflicts... ['127.0.0.1:44817', '178.63.77.181:44817', '127.0.0.1:0']
> [CSRV] Setting kernel resource limits
> [CSRV] Switching to unprivileged server user
> [CSRV] Executing Java...
> 2021-08-15 16:21:20,377 main WARN Advanced terminal features are not available in this environment
> [16:21:20] ain/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.1.25, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
> [16:21:20] ain/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_201 by Oracle Corporation
> [16:21:20] ain/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
> [16:21:20] ain/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: /home/servers/886214/mods/OptiFine_1.16.5_HD_U_G8.jar
> [16:21:20] ain/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
> [16:21:20] ain/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
> [16:21:20] ain/INFO] ixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/servers/886214/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER
> [16:21:20] ain/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
> [16:21:21] ain/ERROR] [io.gi.ze.op.as.fm.VersionChecker/]: An unexpected issue occurred when checking Forge version: 
> java.awt.HeadlessException: 
> No X11 DISPLAY variable was set, but this program performed an operation which requires it.
> 	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204) ~[?:1.8.0_201] {}
> 	at java.awt.Window.<init>(Window.java:536) ~[?:1.8.0_201] {}
> 	at java.awt.Frame.<init>(Frame.java:420) ~[?:1.8.0_201] {}
> 	at java.awt.Frame.<init>(Frame.java:385) ~[?:1.8.0_201] {}
> 	at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1763) ~[?:1.8.0_201] {}
> 	at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1838) ~[?:1.8.0_201] {}
> 	at javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1696) ~[?:1.8.0_201] {}
> 	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:863) ~[?:1.8.0_201] {}
> 	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666) ~[?:1.8.0_201] {}
> 	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637) ~[?:1.8.0_201] {}
> 	at io.github.zekerzhayard.optiforge.asm.fml.VersionChecker.lambda$static$0(VersionChecker.java:35) ~[?:?] {}
> 	at io.github.zekerzhayard.optiforge.asm.fml.VersionChecker.checkForgeVersion(VersionChecker.java:191) ~[?:?] {}
> 	at io.github.zekerzhayard.optiforge.asm.fml.OptiForgeWrapperTransformationService.initialize(OptiForgeWrapperTransformationService.java:87) ~[?:?] {}
> 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68) ~odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107) ~odlauncher-8.0.9.jar:?] {}
> 	at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_201] {}
> 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107) odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59) odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76) odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) odlauncher-8.0.9.jar:?] {}
> 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.1.25.jar:?] {}
> 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.1.25.jar:?] {}
> 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.1.25.jar:?] {}
> [16:21:21] ain/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.transformers
> [16:21:21] ain/INFO] [op.OptiFineTransformer/]: Targets: 311
> [16:21:22] ain/INFO] [op.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
> [16:21:22] ain/INFO] ixin/]: Successfully loaded Mixin Connector [de.maxhenkel.car.MixinConnector]
> [16:21:22] ain/INFO] ixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
> [16:21:22] ain/INFO] ixin/]: Successfully loaded Mixin Connector [de.maxhenkel.camera.MixinConnector]
> [16:21:22] ain/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, .]
> [16:21:28] odloading-worker-1/INFO] [io.gi.ze.op.as.tr.ITransformerImpl/]: Transform: net/minecraft/network/datasync/EntityDataManager
> [16:21:28] odloading-worker-1/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: architectury, class me.shedaniel.architectury.forge.ArchitecturyForge
> java.lang.ExceptionInInitializerError: null
> 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201] {}
> 	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_201] {}
> 	at com.sun.proxy.$Proxy30.<clinit>(Unknown Source) ~[?:?] {}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201] {}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201] {}
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201] {}
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201] {}
> 	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739) ~[?:1.8.0_201] {}
> 	at me.shedaniel.architectury.event.EventFactory.lambda$createInteractionResult$2(EventFactory.java:99) ~[architectury:?] {re:classloading}
> 	at me.shedaniel.architectury.event.EventFactory$EventImpl.update(EventFactory.java:369) ~[architectury:?] {re:classloading}
> 	at me.shedaniel.architectury.event.EventFactory$EventImpl.invoker(EventFactory.java:335) ~[architectury:?] {re:classloading}
> 	at me.shedaniel.architectury.event.EventHandler.registerDelegates(EventHandler.java:68) ~[architectury:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at me.shedaniel.architectury.event.EventHandler.init(EventHandler.java:46) ~[architectury:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at me.shedaniel.architectury.forge.ArchitecturyForge.<init>(ArchitecturyForge.java:33) ~[architectury:?] {re:classloading}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201] {}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201] {}
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201] {}
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201] {}
> 	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_201] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.1] {re:classloading}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) [?:1.8.0_201] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) [?:1.8.0_201] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_201] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_201] {}
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_201] {re:computing_frames}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_201] {}
> Caused by: java.lang.NullPointerException
> 	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1572) ~[asm-9.0.jar:9.0] {}
> 	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546) ~[asm-9.0.jar:9.0] {}
> 	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769) ~[asm-tree-9.0.jar:9.0] {}
> 	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649) ~[asm-tree-9.0.jar:9.0] {}
> 	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452) ~[asm-tree-9.0.jar:9.0] {}
> 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:133) ~odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~odlauncher-8.0.9.jar:?] {re:classloading}
> 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~odlauncher-8.0.9.jar:?] {re:classloading}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201] {}
> 	at net.minecraft.entity.Entity.<clinit>(Entity.java:169) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	... 27 more
> [16:21:28] odloading-worker-1/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 36.1.25, for MC 1.16.5 with MCP 20210115.111550
> [16:21:28] odloading-worker-1/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v36.1.25 Initialized
> [16:21:30] ain/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
> [16:21:30] ain/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 87e8c5e6-7ecf-44d1-9e87-44297d190611
> [16:21:30] ain/INFO] [STDOUT/]: [net.minecraft.crash.CrashReport:func_85057_a:196]: Negative index in crash report handler (16/18)
> [16:21:30] ain/FATAL] [ne.mi.fm.se.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2021-08-15_16.21.30-fml.txt
> ---- Minecraft Crash Report ----
> // Would you like a cupcake?
> Time: 8/15/21 4:21 PM
> Description: Mod loading error has occurred
> java.lang.Exception: Mod Loading has failed
> 	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
> 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
> 	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201] {}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201] {}
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201] {}
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201] {}
> 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.1.25.jar:36.1] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) odlauncher-8.0.9.jar:?] {}
> 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.1.25.jar:?] {}
> 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.1.25.jar:?] {}
> 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.1.25.jar:?] {}
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> -- Head --
> Thread: main
> Stacktrace:
> 	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1572) ~[asm-9.0.jar:9.0] {}
> -- MOD architectury --
> Details:
> 	Caused by 0: java.lang.ExceptionInInitializerError
>  at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201] {}
>  at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_201] {}
>  at com.sun.proxy.$Proxy30.<clinit>(Unknown Source) ~[?:?] {}
>  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201] {}
>  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201] {}
>  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201] {}
>  at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201] {}
>  at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739) ~[?:1.8.0_201] {}
>  at me.shedaniel.architectury.event.EventFactory.lambda$createInteractionResult$2(EventFactory.java:99) ~[architectury:?] {re:classloading}
>  at me.shedaniel.architectury.event.EventFactory$EventImpl.update(EventFactory.java:369) ~[architectury:?] {re:classloading}
>  at me.shedaniel.architectury.event.EventFactory$EventImpl.invoker(EventFactory.java:335) ~[architectury:?] {re:classloading}
>  at me.shedaniel.architectury.event.EventHandler.registerDelegates(EventHandler.java:68) ~[architectury:?] {re:classloading,pl:runtimedistcleaner:A}
>  at me.shedaniel.architectury.event.EventHandler.init(EventHandler.java:46) ~[architectury:?] {re:classloading,pl:runtimedistcleaner:A}
>  at me.shedaniel.architectury.forge.ArchitecturyForge.<init>(ArchitecturyForge.java:33) ~[architectury:?] {re:classloading}
>  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201] {}
>  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201] {}
>  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201] {}
>  at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201] {}
>  at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_201] {}
>  at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.1] {re:classloading}
>  at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
>  at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_201] {}
>  at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_201] {}
>  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_201] {}
>  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_201] {}
>  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_201] {re:computing_frames}
>  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_201] {}
> 	Mod File: architectury-1.20.29-forge.jar
> 	Failure message: Architectury (architectury) has failed to load correctly
>  java.lang.ExceptionInInitializerError: null
> 	Mod Version: 1.20.29
> 	Mod Issue URL: https://github.com/shedaniel/architectury/issues
> 	Exception message: java.lang.NullPointerException
> Stacktrace:
> 	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1572) ~[asm-9.0.jar:9.0] {}
> 	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546) ~[asm-9.0.jar:9.0] {}
> 	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769) ~[asm-tree-9.0.jar:9.0] {}
> 	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649) ~[asm-tree-9.0.jar:9.0] {}
> 	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452) ~[asm-tree-9.0.jar:9.0] {}
> 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:133) ~odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~odlauncher-8.0.9.jar:?] {re:classloading}
> 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~odlauncher-8.0.9.jar:?] {re:classloading}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201] {}
> 	at net.minecraft.entity.Entity.<clinit>(Entity.java:169) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201] {}
> 	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_201] {}
> 	at com.sun.proxy.$Proxy30.<clinit>(Unknown Source) ~[?:?] {}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201] {}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201] {}
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201] {}
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201] {}
> 	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739) ~[?:1.8.0_201] {}
> 	at me.shedaniel.architectury.event.EventFactory.lambda$createInteractionResult$2(EventFactory.java:99) ~[architectury:?] {re:classloading}
> 	at me.shedaniel.architectury.event.EventFactory$EventImpl.update(EventFactory.java:369) ~[architectury:?] {re:classloading}
> 	at me.shedaniel.architectury.event.EventFactory$EventImpl.invoker(EventFactory.java:335) ~[architectury:?] {re:classloading}
> 	at me.shedaniel.architectury.event.EventHandler.registerDelegates(EventHandler.java:68) ~[architectury:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at me.shedaniel.architectury.event.EventHandler.init(EventHandler.java:46) ~[architectury:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at me.shedaniel.architectury.forge.ArchitecturyForge.<init>(ArchitecturyForge.java:33) ~[architectury:?] {re:classloading}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201] {}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201] {}
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201] {}
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201] {}
> 	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_201] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.1] {re:classloading}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_201] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_201] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_201] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_201] {}
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_201] {re:computing_frames}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_201] {}
> -- System Details --
> Details:
> 	Minecraft Version: 1.16.5
> 	Minecraft Version ID: 1.16.5
> 	Operating System: Linux (amd64) version 5.4.0-65-generic
> 	Java Version: 1.8.0_201, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 81061776 bytes (77 MB) / 270008320 bytes (257 MB) up to 7635730432 bytes (7282 MB)
> 	CPUs: 2
> 	JVM Flags: 7 total; -Xms256M -Xmx8192M -XX:MinHeapFreeRatio=2 -XX:MaxHeapFreeRatio=7 -XX:ParallelGCThreads=2 -XX:CICompilerCount=2 -XX:ActiveProcessorCount=2
> 	ModLauncher: 8.0.9+86+master.3cf110c
> 	ModLauncher launch target: fmlserver
> 	ModLauncher naming: srg
> 	ModLauncher services: 
>  /mixin-0.8.2.jar mixin PLUGINSERVICE 
>  /eventbus-4.0.0.jar eventbus PLUGINSERVICE 
>  /forge-1.16.5-36.1.25.jar object_holder_definalize PLUGINSERVICE 
>  /forge-1.16.5-36.1.25.jar runtime_enum_extender PLUGINSERVICE 
>  /accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
>  /forge-1.16.5-36.1.25.jar capability_inject_definalize PLUGINSERVICE 
>  /forge-1.16.5-36.1.25.jar runtimedistcleaner PLUGINSERVICE 
>  /mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
>  /OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
>  /OptiForge-MC1.16.5-0.5.7.jar optiforge TRANSFORMATIONSERVICE 
>  /forge-1.16.5-36.1.25.jar fml TRANSFORMATIONSERVICE 
>  /OptiForge-MC1.16.5-0.5.7.jar FakeOptiFine TRANSFORMATIONSERVICE 
>  /OptiForge-MC1.16.5-0.5.7.jar optiforgewrapper TRANSFORMATIONSERVICE 
> 	FML: 36.1
> 	Forge: net.minecraftforge:36.1.25
> 	FML Language Providers: 
>  javafml@36.1
>  minecraft@1
> 	Crash Report UUID: 87e8c5e6-7ecf-44d1-9e87-44297d190611[16:21:30] ain/FATAL] inecraft/Main]: Failed to start the minecraft server
> net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
> 	Architectury (architectury) has failed to load correctly
> ?7java.lang.ExceptionInInitializerError: null
> ]
> 	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?] {re:classloading}
> 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
> 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) ~[forge:?] {re:classloading}
> 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
> 	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201] {}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201] {}
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201] {}
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201] {}
> 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.1.25.jar:36.1] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) odlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) odlauncher-8.0.9.jar:?] {}
> 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.1.25.jar:?] {}
> 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.1.25.jar:?] {}
> 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.1.25.jar:?] {}
>

**Comment by shedaniel** [comment]
You have optiforge on the server
