### ISSUE TITLE
Memory Leak with REI on dedicated server

### ISSUE THREAD

**Issue by ZYFDroid** [architectury/architectury#131]
[Leak Report generated by eclipse memory analysis tool](https://github.com/ZYFDroid/ZYFDroid/blob/main/contribute/architectury-api/leakreport20210818.zip)

additional clues: class dev.technici4n.fasttransferlib.experimental.impl.item.InventoryWrappersImpl

**Comment by ZYFDroid** [comment]
version info:

Minecraft 1.17.1
fabric-api-0.37.1+1.17
architectury-2.2.21-fabric
RoughlyEnoughItems-6.0.264-alpha-fabric

**Comment by Technici4n** [comment]
Just update indrev for a newer FTL build that fixes this issue.
