### ISSUE TITLE
Platform.getMod and Platform.getOptionalMod throw an exception if the mod isn't loaded

### ISSUE THREAD

**Issue by BasiqueEvangelist** [architectury/architectury#133]
This happens because the `ModImpl` is always constructed if the mod isn't present in the `mods` map, and its constructor asserts that the mod is present via an `Optional.get` call.

**Comment by MaxNeedsSnacks** [comment]
Fixed in #201 (see https://github.com/architectury/architectury-api/pull/201/files#diff-8a63124f0a8e038682ecf885af5aad356c26f8c89b2e5489cc6cc0e422a3defcR157), throwing is intended for getMod but not for getOptionalMod
