### ISSUE TITLE
incompatibility symbol (red "x") in multiplayer menu

### ISSUE THREAD

**Issue by ghost** [architectury/architectury#138]
### To reproduce:
Ping a forge server in the multiplayer menu that does not have Architectury in its mods folder. The client will display a red "x" for incompatible even though you are able to join the server. Is this intended? Because I assumed Architectury is okay to run just client-side.

![redx](https://user-images.githubusercontent.com/82549089/135739918-8c5b8c7a-7466-4ad2-9b58-e5d7da8116eb.JPG)

### Versions:
Forge 1.16.5-36,2,6
Architectury 1.23.33-forge

### From clients latest.log:
_[02Oct2021 22:17:38.148] [Netty Client IO #3/INFO] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Client has mods that are missing on server: [architectury]_

**Comment by MaxNeedsSnacks** [comment]
Certain features in Architectury will require the mod to be installed on the server as well (for example the network system, which mods like KubeJS or the FTB Suite rely on), so this is intentional, yeah

**Comment by MaxNeedsSnacks** [comment]
To clarify, the red X doesn't actually signify anything -- you can still join vanilla servers or Forge servers without Architectury while having it installed; this is just Forge saying that some network data it expected to be there wasn't found
