### ISSUE TITLE
Mods for Minecraft 1.17.x require additional changes for compatibility

### ISSUE THREAD

**Issue by smmmadden** [architectury/architectury#143]
**FYI:** Mostly a reminder than issue since these files are often forgotten to be updated.  There are files to change for 1.17.1 to work.
**mods.toml**, ***mixins*** and **pack.mcmeta** need updating for every major release of Minecraft depending on what is included.
Minecraft 1.17.x - Minimum Java Level Supported: 16.0.1
pack.mcmeta files Pack Format=7 for 1.17.x release, 6 for 1.16 and 5 for 1.15, etc.
Minecraft Vanilla Launcher (new one from Microsoft Store) has loading issues that require additional changes to our mods and modpacks.  Read conversation towards the bottome on CurseForge Support: https://forums.minecraftforge.net/topic/105079-forge-1171-not-launching/?_fromLogin=1
This describes how to workaround the breaking change Microsoft made with the new Vanilla Minecraft launcher

**Comment by shedaniel** [comment]
Yes but what does that have to do with architectury

**Comment by smmmadden** [comment]
I've reviewed the jar file of this mod and found that one or both issues exist for your 1.17.x build.  It means that there are additional changes needed for mods using 1.17.x to ensure they will work.

**Comment by Juuxel** [comment]
The exact "issue" here is the pack format being outdated (6 instead of 7), which is a one line fix.

**Comment by shedaniel** [comment]
Closing this because this is invalid.
PRs for changing the mcmeta file version is welcomed, however that does not cause Forge to fail its bootstrap process.

You seem to be confusing yourself on how Java versions work. Java is generally "forward compatible", which old compiled code can still be ran on newer Java versions.

The issue in your linked forum about how Forge fails is a separate issue and is entirely unrelated to architectury and other mods.

Please refrain from spamming issues about this on architectury and my projects.

**Comment by smmmadden** [comment]
I'm not spamming anything @shedaniel - if you choose not to update the mod, that is entirely up to you.  I've only provided the results of what I see in your mod.  As my first statement starts: FYI which is for your information.  Wasn't opening up a debate on programming practices just providing help on what I've found.  I've been programming for over 35 years, so no I am not confused.  Sorry you feel like I'm spamming you, but please understand I am not.  It's an FYI.

**Comment by shedaniel** [comment]
Sorry for coming out too rude in my previous comment. Architectury and my other mods that are marked as 1.17 already works on 1.17.

**Comment by smmmadden** [comment]
it's all good here, no worries.  Just being a team player :-)  Have a great weekend!
