### ISSUE TITLE
1.26.42 Crashes

### ISSUE THREAD

**Issue by QueueAmI** [architectury/architectury#161]
1.26.42 crashes with unexpected error, Exit Code: 0. I have removed all mods except for architectury and get the same error. I am running fabric-loader-0.11.7-1.16.5.

**Comment by QueueAmI** [comment]
Update: I have tried multiple older version and get the same errors. I went further back and get an error stating that there are entry point errors.

**Comment by shedaniel** [comment]
Duplicate of #151
