### ISSUE TITLE
Add registry key / resource location based feature registration for BiomeModification

### ISSUE THREAD

**Issue by itsmeow** [architectury/architectury#163]
This is a feature of the 1.18 Fabric BiomeModifications implementation, you can pass a key instead of a PlacedFeature to addFeature - this allows mods to use the datapack system for features instead of doing it in code.

**Comment by shedaniel** [comment]
Not possible with forge I believe

**Comment by itsmeow** [comment]
It is with mixins

**Comment by shedaniel** [comment]
We accept PRs :p
