### ISSUE TITLE
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_309 failed

### ISSUE THREAD

**Issue by GGamer6458** [architectury/architectury#169]
Minecraft crashes with Architectury v1.27.46.
No crash with Architectury v1.26.37, including mods listed below.
[crash-2021-12-30_01.32.58-client.txt](https://github.com/architectury/architectury-api/files/7791090/crash-2021-12-30_01.32.58-client.txt)

Minecraft version: 1.16.5
Mods used when crash happened:
![Mods used when crash happened](https://user-images.githubusercontent.com/72705840/147712940-fce29d6e-42e3-486e-8c89-f558cce6624e.png)

**Comment by MaxNeedsSnacks** [comment]
This is unrelated to Architectury. Please report this to the author of Cloth API instead ( cc @shedaniel )

`cloth-client-events-v0.mixins.json:MixinKeyboard`
