### ISSUE TITLE
1.16.5 Minecraft crashes with latest Fabric API, Cloth API and Architectury API:

### ISSUE THREAD

**Issue by ghost** [architectury/architectury#175]
Fabric API 0.42.0  Cloth API 1.5.50  Architectury API 1.28.48
I use MultiMC

Somehow it works fine with Architectury 1.26.42

[crash-2022-01-07_11.48.15-client.txt](https://github.com/architectury/architectury-api/files/7827627/crash-2022-01-07_11.48.15-client.txt)
[latest.log](https://github.com/architectury/architectury-api/files/7827705/latest.log)

**Comment by Juuxel** [comment]
This is an issue with Cloth.
