### ISSUE TITLE
Architectury 1.16.5 v1.28.48 crashes when something explodes

### ISSUE THREAD

**Issue by SidTheMaster** [architectury/architectury#182]
Great api helping with many mods. But the latest version of 1.16.5 which is for fabric has some issues I have it with some mods and whenever something explodes like a creeper explosion or tnt explosion the server just crashes and in the log it says about architectury being the issue. The same happens in singleplayer and the whole minecraft crashes when something explodes. It would be great if it can be fixed. Thank you
![unknown](https://user-images.githubusercontent.com/98372917/150909405-02678d79-b424-4f8a-9d46-898b9d3bc1a7.png)

**Comment by shedaniel** [comment]
Can you provide the full log?

**Comment by SidTheMaster** [comment]
Do I just copy paste the full log bere?

**Comment by SidTheMaster** [comment]
> Can you provide the full log?

Here's the log
[log.txt](https://github.com/architectury/architectury-api/files/7930879/log.txt)

**Comment by LonelyMusicDisc** [comment]
can confirm it happens to me too, here's my log if it helps at all
https://pastebin.com/1YsrkzCm

**Comment by MaxNeedsSnacks** [comment]
Merging into #174
