### ISSUE TITLE
Unable to join world on server

### ISSUE THREAD

**Issue by Asveste** [architectury/architectury#186]
As already said in the title I am unable to join the world on my server. The server is able to start completely fine, but after joining the world it just says "Internal server error".
The guys at the forge forums told me it has something to do with architectury, so that's why I'm reporting it here.

Below I'm attaching the latest log and debug log from the server.

Latest Log: https://gist.github.com/Asveste/bdfb530f126f744eb9616f3b9dea07b6

Debug Log: https://gist.github.com/Asveste/acef1fae9ec0911172f4b04375197965

MC Version: 1.16.5
Forge Version: 36.2.23
Architectury Version: 1.28.48

**Comment by shedaniel** [comment]
Not caused by architectury, I wonder who on the forums is giving false advices, please report this issue to either FTB Chunks or FTB Library, chunks is using a function in library that is crashing, so I am not sure which one is at fault here.

**Comment by Asveste** [comment]
Alright, thanks for the very quick answer.
Also I apologize for the wrong post.
