### ISSUE TITLE
Crash: Mod Incompatibility

### ISSUE THREAD

**Issue by Atlantispy** [architectury/architectury#190]
Hi, 

Have reported to them as well, but using the 7.2.9 version of world edit will cause Architectury to run incorrectly (both 3.4.9 which is the current build in Atlan SMP modpack, and the latest build), and crash.

**Comment by Atlantispy** [comment]
[crash-2022-02-01_10.59.35-fml.txt](https://github.com/architectury/architectury-api/files/7979911/crash-2022-02-01_10.59.35-fml.txt)

**Comment by shedaniel** [comment]
Duplicate of #135
