### ISSUE TITLE
Forge Particle Registration

### ISSUE THREAD

**Issue by jmilthedude** [architectury/architectury#199]
Hi, I opened a PR which resolves this issue, but it does not resolve the issue how the project managers would prefer. Therefore, I am opening this issue and will reference the PR so that you can take a look and potentially resolve the problem in the future your own way. Simply adding this to track the issue.

The problem: 
when registering particles, the implementation as noted in the api does not work. The particles load in Fabric fine, but not in Forge.

The Resolution:
1. The event which registration is called happens too late in the forge lifecycle. The deferred Registry is created in ClientSetup which is too late. Need an earlier point in the Forge Lifecycle. 

2. The ParticleFactoryRegistryEvent needs to be used. This is actually implemented but incorrectly in the ParticleProviderRegistry implementation. The event is subscribed but is never called because it is on the wrong bus. Which should be Bus.MOD). See https://github.com/architectury/architectury-api/blob/917b70d50a89695270d4f6289231c413b6f24bd5/forge/src/main/java/dev/architectury/registry/client/particle/forge/ParticleProviderRegistryImpl.java#L101

**Comment by jmilthedude** [comment]
PR #196 is how I fixed it. You can go off of that if you like.

**Comment by MaxNeedsSnacks** [comment]
Forgot to close this when #305 was merged, whoops
