### ISSUE TITLE
[=1.18.1][≥0.13.0]API hates OptiFabric / OptiFine

### ISSUE THREAD

**Issue by Hebgbs** [architectury/architectury#200]
After hours of research, I've determined that the API is what's stopping me from using anything ≥1.13.0 for 1.18.1 because it always crashes unless I remove it, while using OptiFabric and OptiFine.

I was about to blame Light Overlay for this until I committed another half-hour of troubleshooting, hence how I determined that Architectury API is the trouble causing my suite of mods to not be functional.

Otherwise, using Fabric 0.12.12 is the fix for now.

**Comment by shedaniel** [comment]
Duplication #195 
Just a heads up for everyone else, if this keeps happening for another 2 weeks I will add breaks to optifabric in future versions of architectury until they have fixed it so people don't have to research hours into finding that this is wrong.

**Comment by Hebgbs** [comment]
The strange thing is OptiFabric _isn't_ breaking Architectury. It's something specific with OptiFine in Fabric 0.13.0 and greater _with Architectury_. Because I ran the game without OptiFIne jar _but also_ with OptiFabric. Aside from the warn that comes up which literally makes the game unplayable because of no OptiFine for use with OptiFabric the game launches.

So I am unsure what the problem is, without a full comprehension of how OptiFabric modifies OptiFine. I have created an issue on Chocohead's repo, let's see what happens.

**Comment by Juuxel** [comment]
It's most likely this issue: https://github.com/Chocohead/OptiFabric/issues/598

**Comment by Hebgbs** [comment]
Thank you for the insight.

**Comment by Hebgbs** [comment]
Still issues with OptiFabric 1.12.10 on Fabric 0.13.3 after API has been updated to work past 0.12.12 _last I checked._

I'll confirm and respond later if the issue occurs without extraneous mods using a "Clean" instance.

**Comment by Juuxel** [comment]
Yes, there have been no Optifabric updates to fix the crashes so it still will not work.
