### ISSUE TITLE
URGENT: [Fabric 1.18(.1)] v3.7.20 CRASHES.

### ISSUE THREAD

**Issue by VWRhyme** [architectury/architectury#205]
Hey there - just tried updating everything in my modlist and found that this crashes. No explanation given as to why. It just crashes right on bootup with error.

**Comment by VWRhyme** [comment]
Update: 3.6.17 for 1.18.1 also crashes as well.

v3.4.9 works as intended. Not sure what's causing the issue.

**Comment by shedaniel** [comment]
We have released a fix. If it is still crashes, please attach a crash report or a log.
