### ISSUE TITLE
Drawing a texture makes it bold on Fabric in ClientGuiEvent.RENDER_HUD

### ISSUE THREAD

**Issue by Picono435** [architectury/architectury#210]
Code:
```java
ClientGuiEvent.RENDER_HUD.register(((matrices, tickDelta) -> {
  RenderSystem.setShaderTexture(0, TEXTURE);
  RenderSystem.setShaderColor(1.0F, 0.5F, 0.0F, 1.0F);
  int x = MinecraftClient.getInstance().getWindow().getScaledWidth() / 2 - 25;
  DrawableHelper.drawTexture(matrices, x, 5, 50, 16, 0, 0, 200, 66, 200, 66);
}));
```

This:
![image](https://user-images.githubusercontent.com/57836766/155359037-c8a08cc9-e067-475c-bf8a-2e394f3e5821.png)
Becomes this:
![image](https://user-images.githubusercontent.com/57836766/155359010-7b7ff065-ca49-4d19-941f-21539328f16d.png)

What is also weird is that it works just fine on Forge and in Fabric there are some frames where it goes back to normal, going to back to the weird state again quickly.

**Comment by Juuxel** [comment]
You might have to set the shader manually as well to prevent any weird leakage from other render calls (so `RenderSystem.setShader(GameRenderer::getPositionTexShader)`), try to see if that helps

**Comment by Picono435** [comment]
That seems to fix it, thank you.
