### ISSUE TITLE
architectury has fail to load correctly

### ISSUE THREAD

**Issue by Danielcpu17** [architectury/architectury#213]
java.Lang.RuntimeException: Error computing listener list for
i need help i can't get into the game idk how to solve this
please help is possible thank you

**Comment by MaxNeedsSnacks** [comment]
Do you have logs or any other information that could help us solve the issue at the ready by any chance? This issue doesn't tell us much unfortunately

**Comment by shedaniel** [comment]
Please re-open the issue with logs, closing this as this is stale
