### ISSUE TITLE
Architectury Problem

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [architectury/architectury#215]
I get this crash.
[crash-2022-03-04_16.05.20-client.txt](https://github.com/architectury/architectury-api/files/8189375/crash-2022-03-04_16.05.20-client.txt)

**Comment by ENTPRESTIGIOUS** [comment]
Mod List:
3dSkinLayers-Fabric-1.3.1.jar
 BetterChristmasChests-3.0.0.jar
 Boat-Item-View-Fabric-1.18-0.0.3.jar
 Clumps-fabric-1.18.2-8.0.0+6.jar
 Controlling-fabric-1.18.2-9.0+16.jar
 CraftPresence-Fabric-1.18.2-Release-1.8.8.jar
 DynamicSoundFilters-1.3.0+1.18.jar
 EditSign-1.18.2-2.3.0.jar
 EnchantmentDescriptions-Fabric-1.18.1-9.0.11.jar
 Essential.jar
 Fabric-1.18-SmoothSwapping-0.4.4.jar
 FabricCustomCursorMod-1.3.1.jar
 ForgeConfigAPIPort-v3.2.0-1.18.2-Fabric.jar
'InventoryHUD-fabric-[1.18]+-3.4.2.jar'
 KronHUD-2.0.1.jar
 PetOwner-1.8.2-1.18-pre4+.jar
 PresenceFootsteps-1.4.0.jar
 RoughlyEnoughItems-8.0.442.jar
 XaerosWorldMap_1.20.3.1_Fabric_1.18.2.jar
 Xaeros_Minimap_22.3.0_Fabric_1.18.2.jar
 appleskin-fabric-mc1.18.1-2.3.0.jar
 architectury-4.0.30.jar
 armorchroma-1.2.0.jar
 balm-fabric-2.4.1+0.jar
 betterbeds-1.2.0.jar
 boosted-brightness-2.1.0.jar
 brb-Fabric-1.5.6.jar
 cloth-api-3.2.64.jar
 cloth-config-6.2.57-fabric.jar
 craftingtweaks-fabric-1.18-13.0.0.jar
 cullleaves-2.3.2.jar
 customfov-fabric-1.4.1-1.18.1.jar
 dark-loading-screen-1.6.11.jar
 deathlog-0.2.7+1.18.jar
 durabilitytooltip-1.1.0-mc1.18.jar
 effective-1.1.jar
 fabric-api-0.47.8+1.18.2.jar
 fabric-language-kotlin-1.7.1+kotlin.1.6.10.jar
 fast-chest-1.2+1.18.jar
 ferritecore-4.2.0-fabric.jar
 iris-mc1.18.2-1.2.1-rc2-0cc372f0-dirty.jar
 itemscroller-fabric-1.18.2-0.16.0.jar
 lambdynamiclights-2.1.0+1.17.jar
 lazydfu-0.1.2.jar
 lithium-fabric-mc1.18.2-0.7.9.jar
 logical_zoom-0.0.14.jar
 malilib-fabric-1.18.2-0.12.0.jar
 modmanager-1.2.2+1.18.jar
 modmenu-3.0.1.jar
 modmenu-3.1.0.jar
 physics-mod-2.6.7-mc-1.18-fabric.jar
 pinglist-1.3.3.jar
 playtimer-fabric-1.1.1.jar
 reeses_sodium_options-mc1.18.2-1.4.1.jar
 signtools-fabric.1.18-1.0.0.jar
 sodium-fabric-mc1.18.2-0.4.1+build.15.jar
 starlight-1.0.2+fabric.89b8d9f.jar
 statuseffecttimer-1.1.0+1.18.1.jar
 torohealth-1.18-fabric-2.jar
 trinkets-3.3.0.jar
 tweakeroo-fabric-1.18.2-0.13.0.jar

**Comment by triphora** [comment]
report to "balm-fabric", this isn't architectury's fault

**Comment by ENTPRESTIGIOUS** [comment]
> report to "balm-fabric", this isn't architectury's fault

Thanks!
Freakin dislike these error logs.
