### ISSUE TITLE
Crash on launch with Minecraft v1.18.2

### ISSUE THREAD

**Issue by BrekiTomasson** [architectury/architectury#217]
Using Architectury v3.7.31, getting this in the crash log:

Mixin apply for mod architectury failed architectury.mixins.json:client.MixinMinecraft -> net.minecraft.class_310: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on leftClickAir could not find any targets matching 'Lnet/minecraft/class_310;method_1536()V' in net.minecraft.class_310. Using refmap architectury-fabric-refmap.json [PREINJECT Applicator Phase -> architectury.mixins.json:client.MixinMinecraft -> Prepare Injections ->  -> handler$zej000$leftClickAir(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on leftClickAir could not find any targets matching 'Lnet/minecraft/class_310;method_1536()V' in net.minecraft.class_310. Using refmap architectury-fabric-refmap.json [PREINJECT Applicator Phase -> architectury.mixins.json:client.MixinMinecraft -> Prepare Injections ->  -> handler$zej000$leftClickAir(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]

**Comment by triphora** [comment]
1.18.2 has [a separate release](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric/files/3671589)
1.x -> MC 1.16.x
2.x -> MC 1.17.x
3.x -> MC 1.18.1
4.x -> MC 1.18.2
5.x -> MC 1.19.x
