### ISSUE TITLE
ModelPredicateProviderRegistry only private in common.

### ISSUE THREAD

**Issue by zaide-chris** [architectury/architectury#219]
Both Forge and the Fabric Api use an accessWidener to make `ModelPredicateProviderRegistry.register(Identifier id, UnclampedModelPredicateProvider provider)` and `ModelPredicateProviderRegistry.register(Item item, Identifier id, UnclampedModelPredicateProvider provider)` public.
They should be be made public in the common sub project too so uncommon code isn't required in a mod to access them.

**Comment by shedaniel** [comment]
No, forge modifies `ItemProperties.registerGeneric`'s method signature, making them not binary compatible, use architectury API's `ItemPropertiesRegistry` abtraction.
