### ISSUE TITLE
Failed to load correctly(1.18.1)

### ISSUE THREAD

**Issue by vKILLZONEv** [architectury/architectury#221]
I know there is another issue here reporting the same thing, but I thought it'd be helpful to have a crash log.  Here you go

[crash-2022-03-18_06.14.45-fml.txt](https://github.com/architectury/architectury-api/files/8303631/crash-2022-03-18_06.14.45-fml.txt)
.

**Comment by MaxNeedsSnacks** [comment]
This issue is unrelated to Architectury, please report this to "Apocalypse Origins" instead

c.f. error message saying 
`The Mod File C:\Users\knigh\curseforge\minecraft\Instances\Magic Test\mods\apocalypse_origins-0.1.93.jar has mods that were not found`
