### ISSUE TITLE
[Minor Issue] 5.1.1 on curseforge is tagged for 1.18.2, yet the jar itself is for 1.19

### ISSUE THREAD

**Issue by Merith-TK** [architectury/architectury#223]
https://www.curseforge.com/minecraft/mc-mods/architectury-fabric/files/3699670
![image](https://user-images.githubusercontent.com/10422110/159128887-ef30d617-7503-4100-8314-a2592d99f2cc.png)

the file is tagged for 1.18, but is for 1.19

**Comment by triphora** [comment]
This has been fixed, thanks for reporting!
