### ISSUE TITLE
Incompatible mod set

### ISSUE THREAD

**Issue by Nivo12** [architectury/architectury#224]
Hey there, I am just trying to load a light level mod (https://pcminecraft-mods.com/light-overlay-mod-minecraft-1-14-2/#google_vignette) at it apparently needs architectury as a dependency. I was wondering what I could do because I have the latest of both architectury and optifabric (which seem to be the conflict).

Here is the error code...
----------------------------------------------------------------------------------------------------------------------------------------------------
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Architectury' (architectury) 4.0.29 with version 2- or later that is compatible with:
		 - optifabric 1.12.10
Unmet dependency listing:
	 - Mod 'Architectury' (architectury) 4.0.29 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
----------------------------------------------------------------------------------------------------------------------------------------------------
Thanks for your time!

**Comment by triphora** [comment]
OptiFabric is not supported; this is not something we can fix. See Chocohead/OptiFabric#598
