### ISSUE TITLE
Crash on 1.18.2

### ISSUE THREAD

**Issue by Whitebrim** [architectury/architectury#229]
Trying to migrate from, 1.18.1 to 1.18.2 and got
`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'architectury'!`

Stacktrace: https://pastebin.com/QYXMZVSd

**Comment by topia** [comment]
in provided stacktrace, I think it was caused by worldedit.

**Comment by Whitebrim** [comment]
> in provided stacktrace, I think it was caused by worldedit.

I'll try downgrading it or something

**Comment by Whitebrim** [comment]
> I'll try downgrading it or something

~~downgrading~~ upgrading. It was outdated for 1.18.1. Thank you, @topia
