### ISSUE TITLE
Incompatibility with Oculus/Rubidium

### ISSUE THREAD

**Issue by drakosoldier298** [architectury/architectury#230]
When loading Oculus 1.2.2a with architectuary 3.7.37 it seems to freak out.

https://0x0.st/oqfQ.txt

Ive experienced that even with not enough crashes its unplayable as then if your PC doesn't crash the games text renders as unknown font, which is just rectangles.

**Comment by shedaniel** [comment]
You are using Architectury for 1.18.1 on 1.18.2
