### ISSUE TITLE
Fabric crashes when using both Architectury and OptiFabric

### ISSUE THREAD

**Issue by ghost** [architectury/architectury#233]
These mods work fine.
![image](https://user-images.githubusercontent.com/90461313/161388148-6fbc21f4-8e6f-4674-9258-046559fd995e.png)

These mods, also work fine.
![image](https://user-images.githubusercontent.com/90461313/161388161-bdc899ea-bfa7-44c9-ad3e-4c9c7080bc4f.png)

These mods together, don't work fine.
![image](https://user-images.githubusercontent.com/90461313/161388182-72e8dce0-f786-4122-b363-fe71d21ce133.png)

Using fabric-loader-0.13.3-1.18.1, here's the log that comes with when it crashes.
[latest.log](https://github.com/architectury/architectury-api/files/8402726/latest.log)

It's not a Fabric Crash, it's from my Minecraft. But why does it crash, I do not know.

**Comment by MaxNeedsSnacks** [comment]
#226
