### ISSUE TITLE
Crash with Optifabric

### ISSUE THREAD

**Issue by SunnySlopes** [architectury/architectury#239]
I'm using: Minecraft 1.17.1
Fabric Loader 0.13.3
Optifabric 1.13.0
Fabric API 0.45.0
Architectury API 2.10.8
and the game failed to start with this error:
![20220411083647](https://user-images.githubusercontent.com/49802219/162647258-07af3da1-f8a8-4f01-b2e8-a26a046eebf4.png)
and here's the log:
[latest.log](https://github.com/architectury/architectury-api/files/8460275/latest.log)

**Comment by triphora** [comment]
OptiFine is not supported, has never been supported, and will never be supported -- if it works, it works, but if it doesn't, we aren't going to do anything about it
https://lambdaurora.dev/optifine_alternatives/
