### ISSUE TITLE
crash on newest version 1.16.5

### ISSUE THREAD

**Issue by Jetpack-Cat** [architectury/architectury#246]
https://gist.github.com/Jetpack-Cat/e95284970d28b72bf981010bbd86d097

**Comment by triphora** [comment]
Are you sure this is Architectury's fault? It looks to be the fault of `musictriggers`

**Comment by Jetpack-Cat** [comment]
oh it may be, I had just updated architectury and I saw a line mentioning it, i tried again and it didn't crash. My fault.
