### ISSUE TITLE
Rendering screen crash @ java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Laifsyn** [architectury/architectury#249]
[crash-2022-05-01_08.41.59-client.txt](https://github.com/architectury/architectury-api/files/8599040/crash-2022-05-01_08.41.59-client.txt)
It looks similar to that one where I could kinda consistently get by opening Inventory right about after reloading. Don't know if they're related

**Comment by MaxNeedsSnacks** [comment]
This is likely not an issue with Architectury itself, but with one of the mods using it. Better error handling is something that's been on the backburner for a while now, but for now, you're likely going to have to look for the mod that's breaking yourself (for example by "binary searching" through your modlist, i.e. disabling half of your mods and seeing if the problem persists)
