### ISSUE TITLE
Game crashing when i go near a village and im not entirely sure why

### ISSUE THREAD

**Issue by ShowyCentaur** [architectury/architectury#255]
[crash-2022-05-06_06.23.10-server.txt](https://github.com/architectury/architectury-api/files/8641367/crash-2022-05-06_06.23.10-server.txt)

**Comment by sashaironfist** [comment]
you have a lot of mods dude
i'm guessing its the mods but idk how it REally is

**Comment by MaxNeedsSnacks** [comment]
This is likely not an issue with Architectury itself, but with one of the mods using it. Better error handling is something that's been on the backburner for a while now, but for now, you're likely going to have to look for the mod that's breaking yourself (for example by "binary searching" through your modlist, i.e. disabling half of your mods and seeing if the problem persists)
