### ISSUE TITLE
PlayerHooks.isFake always returns false on fabric

### ISSUE THREAD

**Issue by TropheusJ** [architectury/architectury#261]
FTB Teams uses this hook to check if a player is fake. Create uses [Fake Player API](https://github.com/CafeteriaGuild/fake-player-api) for the fake players of several blocks. Since the result is always false, FTB Teams believes the players are not fake, and crashes.
Create issue: https://github.com/Fabricators-of-Create/Create/issues/307

**Comment by shedaniel** [comment]
Depends on #202

**Comment by Technici4n** [comment]
This is the check we use in AE2 btw:
```java
    public static boolean isFakePlayer(Player player) {
        return player instanceof ServerPlayer && player.getClass() != ServerPlayer.class;
    }
```

**Comment by MaxNeedsSnacks** [comment]
> This is the check we use in AE2 btw:
> 
> ```java
>     public static boolean isFakePlayer(Player player) {
>         return player instanceof ServerPlayer && player.getClass() != ServerPlayer.class;
>     }
> ```

I would say that this is a reasonable "default" expectation, and if mods have custom ServerPlayer subclasses that **are not** fake players, they can use the event described in 202
