### ISSUE TITLE
Mod architectury requires Minecraft 1.18, below 1.18.2

### ISSUE THREAD

**Issue by chortle3** [architectury/architectury#264]
![error](https://user-images.githubusercontent.com/94771839/169929184-c0778743-e206-4b5b-b8cc-7be8f6e2f187.png)
Hi developers of Architectury Api,
I was playing on Minecraft Forge 1.18.2 while this came up.

Please fix this and make this compatible for Minecraft 1.18.2

**Comment by chortle3** [comment]
[crash-2022-05-24_08.17.25-fml.txt](https://github.com/architectury/architectury-api/files/8758854/crash-2022-05-24_08.17.25-fml.txt)
crash report here

**Comment by MaxNeedsSnacks** [comment]
You are using an incorrect version of Architectury, meant for 1.18 and 1.18.1.

Please use Architectury builds starting with **4** for 1.18.2 (should also be on CurseForge / Modrinth)
