### ISSUE TITLE
Architectury API crashes MineCraft with exit code 1

### ISSUE THREAD

**Issue by MeIsPaul** [architectury/architectury#275]
I am attempting to open Minecraft (forge) with the Architectury API. It crashes with exit code 1; when I remove the aforementioned mod from the mods folder, Minecraft starts fine.
It is on a Windows 11 machine with the latest recommended version of Java and latest version of Forge.
Two other mods have installed without error ( conveyer belt and corpse ).
attached are the crash report and latest log from the last failed attempt to start Minecraft:
[crash-2022-06-11_08.14.42-fml.txt](https://github.com/architectury/architectury-api/files/8884308/crash-2022-06-11_08.14.42-fml.txt)
[latest.log](https://github.com/architectury/architectury-api/files/8884310/latest.log)

If you need anything else to help solve this I will do my best to get it to you. 
TIA

**Comment by MaxNeedsSnacks** [comment]
`[11Jun2022 08:14:11.338] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod �eftblibrary�r requires �6architectury�r �o3.1.45 or above�r
�7Currently, �6architectury�r�7 is �o�nnot installed`

You likely have either the Fabric version of Architectury installed, or don't have Architectury at all. Can you please verify that you actually have the *Forge* JAR of the mod? :P

**Comment by MeIsPaul** [comment]
This is what I have: architectury-5.6.22.jar ... downloaded from curseforge.com
If it is not the right one then where do I find the right one? This is the only one that came up from search.
And why are you sticking your tongue out at me?  :-)

**Comment by triphora** [comment]
5.x is for 1.19, use 4.x for 1.18.2

**Comment by MeIsPaul** [comment]
Thank you wafflecoffee, using 4.4.70 worked!
