### ISSUE TITLE
Architectury is the only mod installed and it crashes. 

### ISSUE THREAD

**Issue by CocaColaCan36** [architectury/architectury#279]
I literally only have architectury in because I deduced that it was the only mod causing the crash.
[crash-2022-06-14_21.57.49-client.txt](https://github.com/architectury/architectury-api/files/8905080/crash-2022-06-14_21.57.49-client.txt)
 
Not really sure what the crash report means, it just says the game crashed whilst rendering overlay.

**Comment by tomycabre** [comment]
I have the exact same problem since yesterday, still no sing of a fix, we need to wait until further architectury updates for 1.19 as it is very new and this is expected to happen.

**Comment by shedaniel** [comment]
Duplicate of #278
