### ISSUE TITLE
[Fluids] ArchitecturyFlowingFluid cannot be accessed from outside package

### ISSUE THREAD

**Issue by Slexom** [architectury/architectury#285]
Moving to architecury fluid api, I'm extending _ArchitecturyFlowingFluid_ because I need to override some method.
The resulting class is [this](https://gist.github.com/Slexom/871fd1f529a2bb401cd7846e607822f2).
I'm receiving the following error on calling `super` inside the constructor: 
```
'ArchitecturyFlowingFluid(dev.architectury.core.fluid.ArchitecturyFluidAttributes)' is not public in 'dev.architectury.core.fluid.ArchitecturyFlowingFluid'. Cannot be accessed from outside package
```

**Comment by MaxNeedsSnacks** [comment]
I don't think you should be using the constructor of `ArchitecturyFlowingFluid` directly, rather than subclassing the `Source` and `Flowing` subclasses individually (which both have public constructors)

May I ask what use case you have for specifically subclassing the base class?

**Comment by Slexom** [comment]
As you can see from the gist I've linked, I need to subclass _ArchitecturyFlowingFluid_ to override  _flow_ and _canBeReplacedWith_ methods.

If there is another way to do it, please point it to me. I've seen that the fluid attributes cover most of the configuration needed, but have not found something for the mentioned methods.
