### ISSUE TITLE
Error when trying to join

### ISSUE THREAD

**Issue by LegendLuca** [architectury/architectury#288]
Hello mod developers,
today, when I tryed to join on my server, I got a error, that is caused my Architectury(Like the Forge Teame is saying. in the Attachment I put my server log. Thanks
[2022-06-29-2.log](https://github.com/architectury/architectury-api/files/9013630/2022-06-29-2.log)
!

**Comment by triphora** [comment]
Could be the same issue as #300, not sure yet so not going to close the issue yet

**Comment by triphora** [comment]
Are you still having this issue?

**Comment by triphora** [comment]
Going to take the silence as a no.
