### ISSUE TITLE
So basically, the 1.19 file for Fabric has a wicked virus...

### ISSUE THREAD

**Issue by PepperPlay5** [architectury/architectury#289]
Each time I try to download & use the mod, Trojan:Script/Ulthar.A!ml always come along with that. Is it just me?

**Comment by MaxNeedsSnacks** [comment]
Where are you getting your JARs from? Anywhere other than CurseForge and Modrinth is likely to have been modified and reuploaded by someone else, so we cannot guarantee that those downloads are safe...

**Comment by PepperPlay5** [comment]
> Where are you getting your JARs from? Anywhere other than CurseForge and Modrinth is likely to have been modified and reuploaded by someone else, so we cannot guarantee that those downloads are safe...

Oh really? I did not even know I could get these files from elsewhere.

Well, as it turns out; the infected file I tried to download multiple times was from CurseForge. How about that?

**Comment by PepperPlay5** [comment]
You don't believe me? [See for yourself.](https://www.curseforge.com/minecraft/mc-mods/architectury-api/download/3843623)

**Comment by shedaniel** [comment]
VirusTotal says both 1.19 versions are not infectious:
Forge: https://www.virustotal.com/gui/file/2377271393f664c09529ab1aa9366a82139e69eb0c0a2fbb09a7df8aed7b4ce8
Fabric: https://www.virustotal.com/gui/file/f6ec13c3c9b2bd805ae9b1f67580f97243ba0cad54d3a0bdd9f9303966d0f292

Are you using any uncommon antiviruses that those aren't even listed on VirusTotal?

**Comment by PepperPlay5** [comment]
> 
> Are you using any uncommon antiviruses that those aren't even listed on VirusTotal?

Please don't tell me that Microsoft Defender, which is set as _default_ for **every single Windows 10 device**, is an "uncommon" antivirus.

As I already said, [try downloading one for yourself.](https://www.curseforge.com/minecraft/mc-mods/architectury-api/download/3843623)

**Comment by PepperPlay5** [comment]
![image](https://user-images.githubusercontent.com/108467750/176684317-cf02e73c-bfd9-437f-af24-45dfde8d6672.png)

![image](https://user-images.githubusercontent.com/108467750/176684389-49f1b754-b6bc-48f7-8785-65cd3cfd3ecb.png)

![image](https://user-images.githubusercontent.com/108467750/176684434-867306e0-08dc-425a-8d1f-afde32fa8a85.png)

![image](https://user-images.githubusercontent.com/108467750/176684458-124efe9c-ea11-4958-b599-6d0eeb90038e.png)

**Comment by topia** [comment]
I'm using Microsoft Defender Antivirus (Windows 11 built-in) with any reputation-based options, but I can't replicate your issue.
I tried downloading with your link, but no issue was detected. I also checked SHA256 checksum is the same as virus-total's.

**Comment by PepperPlay5** [comment]
This is outrageous. If using Forge file instead of Fabric doesn't solve this problem for me, I don't know what will.

I'll be in touch as soon as I'm done with _that_.

**Comment by topia** [comment]
Antivirus's machine-learning-based detection (marked as `!ml`) may have some false positives; if you have the same file as ours (please check with [the checksum which showed in virus-total](https://www.virustotal.com/gui/file/f6ec13c3c9b2bd805ae9b1f67580f97243ba0cad54d3a0bdd9f9303966d0f292/details)), I believe you can tell the defender that it's a safe file.

**Comment by shedaniel** [comment]
I have tested the file against Microsoft Security Intelligence, and there is no viruses detected with the latest definition, can you confirm that you have installed all Windows 10 updates so that your Microsoft Defender definition file is not outdated?

**Comment by PepperPlay5** [comment]
> I have tested the file against Microsoft Security Intelligence, and there is no viruses detected with the latest definition, can you confirm that you have installed all Windows 10 updates so that your Microsoft Defender definition file is not outdated?

Everything seems to be working as intended after I got an update. Thanks, I guess?
