### ISSUE TITLE
[1.19.1-pre4] Mixin apply for mod architectury failed architectury.mixins.json:client.MixinLocalPlayer from mod architectury

### ISSUE THREAD

**Issue by kwpugh** [architectury/architectury#293]
I tried updating my mod to 1.19.1-pre4 and it seems to crash on architectury.

Crash report:  https://gist.github.com/kwpugh/71bdfc7a75b5e748d77b8a0813613e0e

My setup:
![Screen Shot 2022-07-08 at 7 13 35 PM](https://user-images.githubusercontent.com/8809210/178083976-8ecbffe1-d9ca-42c2-a718-6e3e24433cd6.png)

**Comment by shedaniel** [comment]
We are not supporting 1.19.1 snapshots yet.
