### ISSUE TITLE
Error Internal Exception with Architectury API

### ISSUE THREAD

**Issue by IceKarma123** [architectury/architectury#294]
I can't play Singleplay mode due to Achitectury-API 5.8.29
It makes my game connection losthttps://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

![This is an error](https://media.discordapp.net/attachments/792769977479856148/995556267319902289/Screenshot_4.png?width=991&height=558)

This is my log [Mylogs] (https://pastebin.com/LHzYKZGD)

**Comment by shedaniel** [comment]
> Error, this is a private paste or is pending moderation.

**Comment by IceKarma123** [comment]
> > Error, this is a private paste or is pending moderation.

Oh sorry, here is new link[New Link](https://studenthcmusedu-my.sharepoint.com/:f:/g/personal/20120340_student_hcmus_edu_vn/Eh2PfVAeel1CuuMCwuzDr4wBEy475Ttu53voR_MIZpuS-A?e=kFJOTE)

**Comment by shedaniel** [comment]
Can you just upload the file here

**Comment by gigabit101** [comment]
This seems to have only started with newer forge versions, Works fine with .64 however updating to the latest seems to have started this issue

**Comment by gigabit101** [comment]
[latest.log](https://github.com/architectury/architectury-api/files/9079211/latest.log)

The worst part is I can't get it to happen in my architectury-api workspace 😕

**Comment by shedaniel** [comment]
Can you test if it is 41.0.70 that broke it? For example, does 41.0.69 work but 41.0.70 not work?

**Comment by gigabit101** [comment]
.69 works, .70 does not

**Comment by gigabit101** [comment]
Ahh, I see 
```
  - 41.0.70 Handle modded packets on the network thread (#8703)
           * Handle modded packets on the network thread
            - On the server we simply need to remove the call to
              ensureRunningOnSameThread.
            - On the client side, we now handle the packet at the very start of the
              call. We make sure we're running from a network thread to prevent
              calling the handling code twice.
              While this does mean we no longer call .release(), in practice this
              doesn't cause any leaks as ClientboundCustomPayloadPacket releases
              for us.
           * Clarify behaviour a little in the documentation
           * Javadoc formatting
           * Add a helper method for handling packets on the main thread
           Also rename the network thread one. Should make it clearer the expected
           behaviour of the two, and make it clearer there's a potentially breaking
           change.
           * Add back consumer() methods
           Also document EventNetworkChannel, to clarify the thread behaviour
           there.
           * Add since = "1.19" to deprecated annotations ```

**Comment by shedaniel** [comment]
As expected from that changelog, thanks for confirming that

**Comment by gigabit101** [comment]
I have tried to track down and fix the issue myself however, my brain is having one of those days where you read something and instantly forget it

**Comment by gigabit101** [comment]
Awesome, Thanks
