### ISSUE TITLE
instant crash 

### ISSUE THREAD

**Issue by mrshomersimpson** [architectury/architectury#296]
using forge version 41.0.94 used new version of architectury ( in order to use light overly) . The game is instantly crashing without loading - crash report attached.

[crash-2022-07-12_14.33.44-client.txt](https://github.com/architectury/architectury-api/files/9093484/crash-2022-07-12_14.33.44-client.txt)

**Comment by shedaniel** [comment]
I believe one of your mods is crashing instead of architectury, there is no mention of architectury in the logs

**Comment by mrshomersimpson** [comment]
Hi there 

Thanks for the reply, perhaps I didnt read the report correctly, i was looking under the detailed walkthrough and noticed this 

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:491) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:

which mentioned architectury. 

I will cycle through my mods now and remove them all adding one by one and see what the issue is. Wondering maybe if its light overlay. 

Thanks so much <3 

EDIT TO ADD: Found the issue, its light overlay which is failing to load correctly. Thank you again
