### ISSUE TITLE
Incompatible with OptiFabric & Optifine

### ISSUE THREAD

**Issue by Mirsario** [architectury/architectury#3]
![image](https://user-images.githubusercontent.com/6795251/100479071-2fff0280-30fe-11eb-86ff-00fc248ad8da.png)
Running this combination of mods on fabric (0.10.8-1.16.4) causes the following crash:
[crash-2020-11-27_22.05.19-client.txt](https://github.com/architectury/architectury/files/5609317/crash-2020-11-27_22.05.19-client.txt)
Not cool nor good.

**Comment by OwenBowen222** [comment]
Same issue here. Waiting for a fix.

**Comment by OwenBowen222** [comment]
I should also note that it seems to be caused by an issue with font rendering
