### ISSUE TITLE
1.19.1 Crash Everytime, using latest version for Fabric

### ISSUE THREAD

**Issue by TheSkyCloud** [architectury/architectury#306]
The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: dev/architectury/event/events/client/ClientChatEvent$ChatProcessor
Exit Code: -1

This is what I receive every time I attempt to start the game. Tried using various versions of your latest releases for fabric, but none change this error from occurring. Would be extremely grateful for any quick assistance you can offer, have a lot of neat mods I'm excited to try that depend on this wonderful mod of yours.

**Comment by triphora** [comment]
No full log = no support.

That being said, someone had this issue in our Discord earlier and they were trying to use the FTB mods on an MC version that they're not updated to. Might be your issue, but we have no way of knowing because you never provided the full log.
