### ISSUE TITLE
Requires Forge 40.1.14?

### ISSUE THREAD

**Issue by Marvinim** [architectury/architectury#308]
![DD39D35E-6717-4417-A2E5-CADAA6390445](https://user-images.githubusercontent.com/110700709/183223129-36d914cf-26a4-4589-b6ff-7bc082e51ae5.jpeg)
I don’t know why but when I get on with arch it’s as for forge 40.1.14 or above. Please help

**Comment by triphora** [comment]
Do as it says, install the correct Forge version...
