### ISSUE TITLE
Attribute Registry wrapper

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [architectury/architectury#31]
(from the [The Big, Fat Update ™️](https://github.com/FTBTeam/FTB-Ultimine/commit/00b9188e266f890364dd8733bdd978311a798673) commit)

Forge uses standard `IForgeRegistry` to register attributes(? actually, a `GlobalEntityTypeAttributes` class exists), while Fabric uses the `FabricDefaultAttributeRegistry`. Perhaps we should wrap this in some way

**Comment by jmendonza** [comment]
Don't know if this helps but this may be used as reference:
Common:
https://github.com/YummyLoop/Yummy/blob/0d8c780208f67613acbb5a04fbe73abeb2c1e578/common/src/main/net/examplemod/registry/EntityAttributeLink.kt
Fabric:
https://github.com/YummyLoop/Yummy/blob/0d8c780208f67613acbb5a04fbe73abeb2c1e578/fabric/src/main/net/examplemod/registry/fabric/EntityAttributeLinkImpl.kt
Forge (deprecated):
https://github.com/YummyLoop/Yummy/blob/0d8c780208f67613acbb5a04fbe73abeb2c1e578/forge/src/main/net/examplemod/registry/forge/EntityAttributeLinkImpl.kt
Forge: 
https://github.com/YummyLoop/Yummy/blob/8f550d46e1dbc11d45ab38fc8a403e7dd13b881b/forge/src/main/net/examplemod/registry/forge/EntityAttributeLinkImpl.kt
