### ISSUE TITLE
STDERR in server startup

### ISSUE THREAD

**Issue by ghost** [architectury/architectury#317]
The error mentions this java.lang.ClassNotFoundException: dev.architectury.utils.fabric.GameInstanceImpl::init

Any ideas what might be causing it? I don't know if its architectury but that is the only mod I see mentioned. Just upgraded to architectury 5.11.38 still on fabricloader 0.14.8 with a few other mods

File
[server-latest.log](https://github.com/architectury/architectury-api/files/9310725/server-latest.log)

**Comment by Juuxel** [comment]
This is a bug in Server Translations API.

They're trying to read resources through the mod classes and assuming that all entrypoints are class names, but they can be method references like ours.

**Comment by ghost** [comment]
> This is a bug in Server Translations API.
> 
> They're trying to read resources through the mod classes and assuming that all entrypoints are class names, but they can be method references like ours.

Ok thanks. I assume that is a module of fabric api and it will be fixed in an upcoming verison of that?
Edit: I thought it was bad practice to use STDERR lol

**Comment by triphora** [comment]
No, it's included within Hey That's Mine. If I remember correctly the devs of Server Translation API are @arthurbambou and @Patbox - report this to their repo.

**Comment by Patbox** [comment]
Try installing this and tell me if it works <https://maven.nucleoid.xyz/fr/catcore/server-translations-api/1.4.16%2B1.19/server-translations-api-1.4.16%2B1.19.jar>

**Comment by ghost** [comment]
> Try installing this and tell me if it works https://maven.nucleoid.xyz/fr/catcore/server-translations-api/1.4.16%2B1.19/server-translations-api-1.4.16%2B1.19.jar

@Patbox same error
[server-latest-2.log](https://github.com/architectury/architectury-api/files/9311059/server-latest-2.log)

**Comment by Patbox** [comment]
Server Translation API + Latest 1.19.2 Architectury loads fine for me. Additionally it doesn't have mixin under `create` method in language files. It might be interaction between some other mods you have. From what I can see it's issue with d4f (Discord4Fabric) mod. See https://github.com/Reimnop/Discord4Fabric/blob/main/src/main/java/me/reimnop/d4f/mixin/LanguageMixin.java
