### ISSUE TITLE
1.17.1 Crash on Title Screen

### ISSUE THREAD

**Issue by InkyLily** [architectury/architectury#321]
I don't know if this is an issue with the version of architectury I was given with the pack or maybe an issue with mixins. Though the error references architectury 2.9.3 in the log.

Time: 8/12/22, 6:10 PM
Description: Rendering screen

org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_757::method_3192(FJZ)V has incompatible changes at opcode 505 in callback architectury.mixins.json:client.MixinGameRenderer from mod architectury->@Inject::renderScreenPre(FJZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IILnet/minecraft/class_4587;)V.
 Expected: [I, I, Lnet/minecraft/class_4587;]
    Found: [I, I, Lnet/minecraft/class_1041;]
Available: [I, I, Lnet/minecraft/class_1041;, Lnet/minecraft/class_1159;, Lnet/minecraft/class_4587;, Lnet/minecraft/class_4587;]
	at net.minecraft.class_757.handler$zin000$renderScreenPre$missing(class_757.java)
	at net.minecraft.class_757.method_3192(class_757.java:874)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.handler$zin000$renderScreenPre$missing(class_757.java)

-- Screen render details --
Details:
	Screen name: xaero.common.gui.GuiWidgetUpdateAll
	Mouse location: Scaled: (425, 88). Absolute: (1701.000000, 354.000000)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4.000000

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, charmonium/journeyman
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3337837736 bytes (3183 MiB) / 7281311744 bytes (6944 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600G with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2507
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24496.97
	Virtual memory used (MB): 21509.39
	Swap memory total (MB): 8205.41
	Swap memory used (MB): 666.92
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 2.2.0
		alaskanativecraft: Alaska Native Craft 1.3.3
		apoli: Apoli 2.0.0
		appleskin: AppleSkin 2.3.0+mc1.17.1
		apugli: Apugli 1.1.5
		architectury: Architectury 2.9.3
		artisanat: Artisanat 2.1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automatone: Automatone 0.4.1
		bannerpp: Banner++ 2.0.4+mc.1.17-rc1
		bclib: BCLib 0.5.6
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterend: Better End 0.12.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.3.14
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		bitsandchisels: BitsAndChisels 2.5.3
		blockus: Blockus 2.2.10+1.17.1
		blue_endless_jankson: jankson 1.2.1
		botania: Botania 1.17.1-422-FABRIC
		calio: Calio 1.0.3
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		castle_dungeons: Castle Dungeons 2.6-1.17-fabric
		cavebiomes: Cave Biomes 0.6.3
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		chime: Chime 1.2.0-SNAPSHOT
		chunky: Chunky 1.2.147
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config2: Cloth Config v5 5.2.47
		cloth-utils-v1: Cloth Utils v1 2.0.54
		collectionorigins1: Imperium Origins Collection 1 2.0
		columns: Columns 1.2.0
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		computercraft: CC:Restitched 1.97.4
		couplings: Couplings 1.5.0+1.17
		croptopia: Croptopia 1.6.1
		ctm: ConnectedTexturesMod for Fabric 0.5.1+1.17
		culinaire: Culinaire 2.1
		dawn: Dawn API 2.0.6
		decimal_coins: Decimal Coins 1.17.1-1.3.0
		earthtojavamobs: Earth2Java 1.7.3+1.17
		eldritch_mobs: Eldritch Mobs 1.9.2
		extraorigins: Extra Origins 1.17-6
		fabric: Fabric API 0.46.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+cf39a74318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+e821752d18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+cf39a74318
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+cf39a74318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+cf39a74318
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+cf39a74318
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+cf39a74318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.1+3447790d18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+cf39a74318
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.15+b556f28c18
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.1+377137cc18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.12+e99fbe1218
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.4+cf39a74318
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+cf39a74318
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+6617390918
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.2+cf39a74318
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.6+2a2bb57318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.4+cf39a74318
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.6+0392f3a618
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+cf39a74318
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+cf39a74318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+cf39a74318
		fabric-models-v0: Fabric Models (v0) 0.3.1+cf39a74318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+cf39a74318
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+cf39a74318
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+cf39a74318
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+f907116918
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+cf39a74318
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+cf39a74318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.0+ea29b33318
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.6+ce16ae5918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.10+ce16ae5918
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+cf39a74318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+cf39a74318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+cf39a74318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+cf39a74318
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+377137cc18
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.1+591a0f2118
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.10+f09604ce18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+cf39a74318
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+cf39a74318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.2.0+48a9ad8918
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.3+cf39a74318
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+cf39a74318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.3+3b96517518
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.4+cf39a74318
		fabricloader: Fabric Loader 0.14.8
		fake-player-api: Fake Player API 0.2.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fermion: Fermion 2.11.244
		fermion-gui: Fermion GUI 2.6.244
		fermion-modkeys: Fermion Modifier Keys 1.10.244
		fermion-orientation: Fermion Orientation 1.2.244
		fermion-simulator: Fermion Simulator 1.8.244
		fermion-varia: Fermion Varia 2.6.244
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.1
		frex: FREX 5.6.255
		geckolib3: Geckolib 3.0.30
		glassential: Glassential 1.17-1.2.0
		graveyard: The Graveyard 2.1
		identity: Identity 1.15.2-1.17.1
		impersonate: Impersonate 2.3.5
		indium: Indium 1.0.0+mc1.17.1
		indrev: Industrial Revolution 1.12.0-BETA
		inventorysorter: Inventory Sorter 1.8.0-1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		json-model-extensions: JSON Model Extensions 1.22.203
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		krypton: Krypton 0.1.4
		kyrptconfig: Kytpt Config 1.1.10-1.17
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.2.1+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.4
		locki: Locki 0.5.1
		lovely_snails: Lovely Snails 1.0.3+1.17
		magna: Magna 0.4.0-1.17.1
		mcdar: MC Dungeons Artifacts 1.4.1
		medievalorigins: Medieval Origins 3.0.2
		minecraft: Minecraft 1.17.1
		mo_glass: Mo Glass 1.5-MC21w41a
		moborigins: Mob Origins 1.6.0
		modmenu: Mod Menu 2.0.14
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		mousetweaks: Mouse Tweaks 2.15
		nibbles: Nibbles 1.1.0
		no_null_processors: No Null Processors - Fabric 1.0.0+1.17.1
		omega-config: OmegaConfig 1.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		origins: Origins 1.1.0
		originsumbrellas: Origins: Umbrellas 1.3.0
		patchouli: Patchouli 1.17.1-59-FABRIC
		pehkui: Pehkui 2.3.0+1.14.4-1.17.1
		playerabilitylib: Pal 1.4.0
		promenade: Promenade 2.1.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.11-beta
		repurposed_structures: Repurposed Structures 2.5.7+1.17.1
		requiem: Requiem 2.0.0-beta.1
		requiem-core: Requiem-Core 2.0.0-beta.1
		requiemapi: Requiem-API 2.0.0-beta.1
		roughlyenoughitems: Roughly Enough Items 6.3.358
		satin: Satin 1.6.4
		shadeorigin: A Shadekin Origin 2.0
		shwfox: Shadew's Foxes 1.1+fabric
		simple-shelves: Simple Shelves 1.0.0
		simpletransport: SimpleTransport 1.0.0-1.17.1
		sodium: Sodium 0.3.2+build.7
		special-circumstances: Special Circumstances 1.9.244
		stacc: Stacc 1.2.3
		starlight: Starlight 1.0.0+fabric.73f6d37
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		structurized: Structurized 1.3.0
		tacocraft: TacoCraft 1.6.4-1.17.1
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.0.11-beta
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		toomanyorigins: TooManyOrigins 0.2.2
		travelersbackpack: Traveler's Backpack 1.17.1-6.0.0
		traverse: Traverse 4.0.0
		trinkets: Trinkets 3.0.4
		voicechat: Simple Voice Chat 1.17.1-1.1.4
		waystones: Waystones 2.0.4
		worldedit: WorldEdit 7.2.7+9f3e795
		xaerominimap: Xaero's Minimap 21.18.0
		xaeroworldmap: Xaero's World Map 1.17.2
		xlpackets: XLPackets 2.0-1.17
		xp_storage: XP Storage 1.4.2+1.17.1
		yungsapi: YUNG's API 1.17-Fabric-19
	Launched Version: fabric-loader-0.14.8-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3050/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.59, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods, charmonium/journeyman, charmonium/journeyman

**Comment by triphora** [comment]
Please try updating to v2.10.12 https://modrinth.com/mod/architectury-api/version/2.10.12%2Bfabric

**Comment by InkyLily** [comment]
> 

That worked, thank you so much!
