### ISSUE TITLE
Mod loading error has occurred (1.18.2, Forge)

### ISSUE THREAD

**Issue by dr3ams** [architectury/architectury#322]
Nor sure if it's Architecture's fault or BiomeMakeover

https://gist.github.com/dr3ams/9c1a107146c601098a11e32a80f716e4

Happens randomly, client usually works after relaunch.

**Comment by Lemonszz** [comment]
Looks similar to #300.
I'll look into it on my end.

**Comment by MaxNeedsSnacks** [comment]
This *should* be an issue with Biome Makeover, has this occurred to you since @dr3ams?

**Comment by dr3ams** [comment]
Wasn't reported since then and we had BiomeMakeover updated. (it's in a modpack and was reported by a player)

**Comment by MaxNeedsSnacks** [comment]
Awesome, I‘m gonna be closing this then for the time being to clean up the issue tracker a little. Feel free to reopen if it happens again ^^
