### ISSUE TITLE
Not working in 1.19.2 bug

### ISSUE THREAD

**Issue by AAAAAA4A** [architectury/architectury#323]
This is a bug that keeps happening to me and maybe other people in 1.19.2

![sya](https://user-images.githubusercontent.com/111311925/184720679-4b92b111-2c6c-4e2d-b024-655a97c96390.png)

**Comment by Juuxel** [comment]
This is not a bug, you need to install [Fabric API](https://curseforge.com/minecraft/mc-mods/fabric-api).

**Comment by AAAAAA4A** [comment]
I have Fabric API though. Oh.. Wrong one 😂
