### ISSUE TITLE
Forge 43.1.1 (1.19.2) - Crash when using chat

### ISSUE THREAD

**Issue by big-julius** [architectury/architectury#324]
Hello,

When anyone on my server try to post a message in the chat : all players connected have their game crashing.
I send the crash report.
[crash-2022-08-21_12.00.30-client.txt](https://github.com/architectury/architectury-api/files/9388838/crash-2022-08-21_12.00.30-client.txt)

**Comment by Quipex** [comment]
I confirm that, the exception occurs on client

```
java.lang.NoSuchMethodError: 'net.minecraft.network.chat.ChatType net.minecraftforge.client.event.ClientChatReceivedEvent.getType()'
	at dev.architectury.event.forge.EventHandlerImplClient.event(EventHandlerImplClient.java:120) ~[architectury-5.12.42-forge.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
```

**Comment by Juuxel** [comment]
On Minecraft 1.19.1 and 1.19.2 you have to use Architectury 6.x, but you have 5.x. Upgrading should fix it.

**Comment by Quipex** [comment]
Thanks! I've downloaded 5.x because it was on top
![image](https://user-images.githubusercontent.com/30311108/185797585-4de1637a-8c22-4159-84aa-13818174db90.png)

**Comment by big-julius** [comment]
Oh sh*t! I did the same mistake... Sorry and thankk you for the reply. ;)
