### ISSUE TITLE
[incompatible] with Fabric 1.19.2

### ISSUE THREAD

**Issue by xR4YM0ND** [architectury/architectury#327]
[latest.log](https://gist.github.com/SpigotDE/7009ac9883b51400a052c2b29ae92967)

**Comment by Juuxel** [comment]
You need to download the 1.19.2 version. https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/3929406

**Comment by xR4YM0ND** [comment]
seen it just now ... my fault
