### ISSUE TITLE
 Crashes on startup in 1.19.2 (with mods, Forge)

### ISSUE THREAD

**Issue by McBlxck** [architectury/architectury#328]
The launcher tries to start the game but then this crash report pops up
![crash ](https://user-images.githubusercontent.com/112269483/187039805-a375a13a-1044-4e33-ac29-8a54b1d0babe.PNG)
Modlist:
![modlist](https://user-images.githubusercontent.com/112269483/187039943-8f2accf5-9e37-433b-a15c-99552e9d5427.PNG)

(Some mods are in 1.19.1 or 1.19 but they work perfectly whitout the architectury mod)

**Comment by Juuxel** [comment]
Please post the full game log (logs/latest.log)  of a screenshot of a small section of it - the error message itself isn't enough to debug this.

**Comment by CoNesTra** [comment]
Having the same issue on Fabric version 0.14.9, on MC version 1.19.2. I know in the screenshot I'm not on the latest version of the mod but it doesn't work on that version either.

Mods:
![image](https://user-images.githubusercontent.com/67205689/187052217-e3a5d9f8-4b89-4e85-8c96-15eaaedbff3b.png)

Log:
https://pastebin.com/Wz2vzRcQ

**Comment by triphora** [comment]
Looks to be an issue with ftblibrary. Report to them and/or make sure it's up to date for the MC version you're using.

**Comment by CoNesTra** [comment]
> Looks to be an issue with ftblibrary. Report to them and/or make sure it's up to date for the MC version you're using.

Will do. Thanks for your quick response!
