### ISSUE TITLE
加载模组，导致游戏崩溃（architectury-6.2.43-forge.jar）

### ISSUE THREAD

**Issue by ChenXi-King** [architectury/architectury#329]
[错误报告-28-8-2022_10.14.14.zip](https://github.com/architectury/architectury-api/files/9438997/-28-8-2022_10.14.14.zip)

**Comment by triphora** [comment]
要么你的FTB库的副本已经过时，要么它与你试图使用的Minecraft版本不兼容。请尝试更新FTB库。

Duplicate of #328

**Comment by ChenXi-King** [comment]
我使用的是最新的FTB库，还是不行。使用的都是1.19.2的模组，应该不会出现版本不兼容的情况

**Comment by triphora** [comment]
FTB库有[1.19的版本](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge/files/3890137)，但没有1.19.2。
