### ISSUE TITLE
cant use on 1.19.2

### ISSUE THREAD

**Issue by pizzav-xyz** [architectury/architectury#331]
![image](https://user-images.githubusercontent.com/103120356/187203084-51a2f027-0f03-4f87-9202-74e42333ae02.png)
pls fix its the only mod that light overlay needs is broken

**Comment by MaxNeedsSnacks** [comment]
You need to use the 1.19.2 version of Architectury API. You can find it using this tool: https://juuxel.github.io/architectury-api-versions/
