### ISSUE TITLE
Unable to start with Fabric

### ISSUE THREAD

**Issue by Fede2782** [architectury/architectury#334]
Hi, when I try to start Fabric with Architectury it doesn't start. It gives this error

[11:24:09] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[11:24:10] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath

But in the config directory, there aren't files. 

Minecraft 1.19.2
Fabric 0.14.9

**Comment by RobertHDPotatoes** [comment]
What was your solution for this? I am having the same issue and can't seem to resolve it.

**Comment by Fede2782** [comment]
I think this is some mods problem because removing some of them this problem is disappeared

**Comment by RobertHDPotatoes** [comment]
After a lot of testing, my issue seemed to be related to a KubeJS update. (In case anyone else stumbles upon this issue)

**Comment by Juuxel** [comment]
> [11:24:09] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[11:24:10] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath

This is just a warning that always occurs even without Architectury, it's not an actual crash.

**Comment by Fede2782** [comment]
But for me, after that the game crashed

**Comment by Juuxel** [comment]
That's not the cause of the crash. I'm pretty sure it's not even related to mods in fact

**Comment by RobertHDPotatoes** [comment]
The cause of the crash (for me) was an outdated compatibility that FTB Quests had with KubeJS, so yes it was quite unrelated, but I was having trouble getting crash logs for a while due to the way it crashes, and as originally mentioned that is the last thing that the latest log shows. Updating KubeJS, FTB Quests and FTB Library fixed this crash for me.
