### ISSUE TITLE
1.19.2 mouseClicked event handler error.

### ISSUE THREAD

**Issue by Axodique** [architectury/architectury#338]
Hello. When I open my world, my game crashes with this message. I've looked at other topics and it was caused by other mods, but I think this one is cause by architectury? It might be fabric API though, I'm not sure.

https://pastebin.com/1T7YuPs2

**Comment by Juuxel** [comment]
You're using an outdated version of Identity.

**Comment by Axodique** [comment]
That worked! Thank you!
