### ISSUE TITLE
Dreamcraft crash when creating a new world

### ISSUE THREAD

**Issue by 7amLoaf** [architectury/architectury#339]
I got the following crash report while trying to create a new world in Dreamcraft on 1.19, v7 release. Crash log is attached below. A single player world gets created but is stuck at 0% indefinitely until the game crashes.

![unknown](https://user-images.githubusercontent.com/113586212/190347480-38cf2396-014c-4db7-ab31-56a24d655b64.png)

[crash-2022-09-15_03.40.43-server.txt](https://github.com/architectury/architectury-api/files/9573095/crash-2022-09-15_03.40.43-server.txt)

**Comment by shedaniel** [comment]
Your Minecraft is running out of memory
