### ISSUE TITLE
fabric file & can't be installed?

### ISSUE THREAD

**Issue by k4tie3** [architectury/architectury#34]
I downloaded this mod specifically for the JEI mod.  That didn't work for survival so I then downloaded the FTB GUI Library mod (it said it in the error message in Minecraft).  
The FTB mod said I needed the architecture mod (this current mod) but when I downloaded that..
(so I now have JEI mod, FTB, and Architectury), it says the architectury one is a fabric file?.  
Can someone help me?

**Comment by shedaniel** [comment]
You probably downloaded the fabric version of architectury, please try to download the forge version.

**Comment by k4tie3** [comment]
> You probably downloaded the fabric version of architectury, please try to download the forge version.

i did that, but now when I go into my inventory at the bottom right it says "There is not enough space to display JEI here."

**Comment by shedaniel** [comment]
That is not an architectury issue.

**Comment by k4tie3** [comment]
> That is not an architectury issue.

I know that but I saw this problem only come up after I downloaded this mod & the FTB one.  So I don't know what specifically is causing this.  If you think it's the JEI mod I can go over to that mod and ask for help :)

**Comment by k4tie3** [comment]
I'll go over to the JEI mod issue page.  Thank you for helping, you helped with the hardest part and I appreciate it. :)
