### ISSUE TITLE
Crash - Ticking memory connection

### ISSUE THREAD

**Issue by Jetpack-Cat** [architectury/architectury#342]
Forge 1.16.5 Latest version of everything
architectury-1.32.66.jar

[crash-2022-09-20_09.10.22-server.txt](https://github.com/architectury/architectury-api/files/9609471/crash-2022-09-20_09.10.22-server.txt)

The game crashed

**Comment by plunginghornets** [comment]
Similar crash in the same version, but considering we have very different mods, I don't know if the cause is the same. Let me know if I need to move this to a new issue.

https://paste.ee/p/umJtq

**Comment by MaxNeedsSnacks** [comment]
Duplicate of #286

**Comment by SiverDX** [comment]
Meant to write this in the open issue
