### ISSUE TITLE
my minecraft suddenly crashes when use architectury  6.2.46 (1.19.2 Forge)

### ISSUE THREAD

**Issue by kirigami318** [architectury/architectury#346]
idk how this happen. i use this mod over 2 week and today suddenly this mod crashes. i dont have any clue for this issue
![Screenshot_600](https://user-images.githubusercontent.com/73990179/197310150-4423a0fc-113a-4d15-a627-fe726a09a427.png)

**Comment by shedaniel** [comment]
To comply with the Minecraft EULA, we do not support or attempt to provide support for TLauncher, I am closing the issue. This can potentially harm the project, please understand.
