### ISSUE TITLE
Game crashes when I use the fabric 1.16.5 version of the mod

### ISSUE THREAD

**Issue by ShadowBoi74** [architectury/architectury#349]
the game crashes when i use the fabric version of the architectury mod 1.16.5. When i use the forge version of it on fabric it runs smoothly. Pls help.
https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/3857642
Btw i am using it in a custom modpack of mine

**Comment by triphora** [comment]
No logs, no screenshots, no service
