### ISSUE TITLE
Conflict with Voxelmap

### ISSUE THREAD

**Issue by Glucy-2** [architectury/architectury#35]
[crash-2021-02-01_11.54.47-client.txt](https://github.com/architectury/architectury-api/files/5901771/crash-2021-02-01_11.54.47-client.txt)

**Comment by shedaniel** [comment]
Can you reproduce this issue **without** architectury and are you able to consistently reproduce the issue **with** architectury?

**Comment by Glucy-2** [comment]
> Can you reproduce this issue **without** architectury and are you able to consistently reproduce the issue **with** architectury?

Yeah,it doesn't crash without architectury or without voxelmap, it only crashes with both architectury and voxelmap installed.

**Comment by PatiTati** [comment]
Same problem here. 1.16.5 with Fabric Loader and API. With Voxel Map the game crashed.
Mods loaded (Optifine, Voxelmap, Fabric API)

**Comment by StarsDown64** [comment]
Same issue here: https://www.curseforge.com/minecraft/mc-mods/voxelmap?comment=2916
