### ISSUE TITLE
Game doesn't start with the mod

### ISSUE THREAD

**Issue by Aurytis11** [architectury/architectury#356]
The game doesn't start because the error says that it needs fabric 0.54.0 but the newest version of fabric is 0.14.11
I've attached a photo as proof
![Screenshot (72)](https://user-images.githubusercontent.com/119624161/205138223-ba8a92ef-e0eb-4e42-949c-4fc111b4e64d.png)

**Comment by triphora** [comment]
[Fabric API](https://modrinth.com/mod/fabric-api) not Fabric Loader

**Comment by Aurytis11** [comment]
i realized that onced i looked at my desktop and saw that for some reason the fabric api that i downloaded was on my desktop and not in my mods folder where i thought it was gonna go
