### ISSUE TITLE
Crash caused with this api

### ISSUE THREAD

**Issue by ClayDK** [architectury/architectury#359]
hello
im currently making a modpack and ive trimmed down a crash error code 1 cause down to this api and ive tried looking up online how to fix it but sadly im now all out of options can i get some help and its forge base so idk what could cause the conflict
[crash-2022-12-05_03.33.40-fml.txt](https://github.com/architectury/architectury-api/files/10150399/crash-2022-12-05_03.33.40-fml.txt)

**Comment by triphora** [comment]
Says in the log that ftbquests requires ftbteams and ftblibrary.

**Comment by ClayDK** [comment]
just saw the reply could've been that the crash report was wrong due to it being one of the times i turned of the api and it working... could you reopen it?

**Comment by topia** [comment]
In that case, I suggest you would like to start by pasting a new crash report.
