### ISSUE TITLE
having issues with the api causing "exit code: 1" crashes and idk how to fix

### ISSUE THREAD

**Issue by ClayDK** [architectury/architectury#360]
hello
im currently making a modpack and ive trimmed down a crash exit code: 1 cause down to this api and ive tried looking up online how to fix it but sadly im now all out of options can i get some help and its forge base so idk what could cause the conflict and ive tried removing the api and that fixed it but sadly this api is used for some of the mods im using and therefor kinda need it you can see the pic ive shared of how it looks after ive tried to run the pack but sadly this is all i see not even a crash report log
![image](https://user-images.githubusercontent.com/101873741/205545597-02219d0e-429a-4c1c-9ed5-ed573953a7e4.png)

**Comment by topia** [comment]
If there is no crash report, you would probably like to check the latest.log.

**Comment by ClayDK** [comment]
ive tried... nothing

**Comment by triphora** [comment]
Please join us on discord and create a thread in player-support instead of making issues here, the issue tracker is meant to be more for tracking bugs and feature requests
https://discord.architectury.dev/

**Comment by ClayDK** [comment]
thanks then
