### ISSUE TITLE
Game crash at launching

### ISSUE THREAD

**Issue by Antonio3400** [architectury/architectury#361]
Hi 
I have the new forge version 44.0.1 and I added the mod better animal plus and my game launch but when I added architectury it says exit code 1 like others incompatible mods (1.19.2) Thank you

**Comment by triphora** [comment]
Provide a crash log or the issue will be closed.

**Comment by triphora** [comment]
Rereading the OP, it looks like you used the wrong version for the MC version you're on. 7.x is for 1.19.3, and 6.x is for 1.19.2.

**Comment by Antonio3400** [comment]
Hello triphora ,

thank you for your answers . What are you saying and what should I do ?

**Comment by Antonio3400** [comment]
I downloaded cidatel, better animal plus , journey map and my game didn’t crash and the mods ( except better animal plus because it requires achitectury) we’re all working fine.

**Comment by triphora** [comment]
Architectury has its own version number which relies on the Minecraft version. 7.x.x is for Minecraft 1.19.3. 6.x.x is for Minecraft 1.19.2. Make one hundred percent sure you're downloading the correct version, and if it still crashes, upload the full latest.log.

**Comment by Antonio3400** [comment]
Oki thanks :)

**Comment by Antonio3400** [comment]
I downloaded the version 7.0.64 and not working
