### ISSUE TITLE
Minecraft crashes during launch

### ISSUE THREAD

**Issue by AdventureLady** [architectury/architectury#362]
I having been trying to run vanilla Minecraft with just a few mods I have added on my own. Right now, I am just using the following:

Roughly Enough Items (1.19.3) - 10.0.578
Architectury-api (1.19.3) - 6.4.62
Cloth Config v9 API (1.19.3) - 9.0.94

I am using the latest version of MultiMc with Forge 44.0.1 and Minecraft 1.19.3 

![crash](https://user-images.githubusercontent.com/29524786/206605248-dd729b29-0295-40c0-bd5f-6c691c25fa29.png)
[crash-2022-12-08_20.40.23-fml.txt](https://github.com/architectury/architectury-api/files/10191146/crash-2022-12-08_20.40.23-fml.txt)

**Comment by triphora** [comment]
You need 7.x for 1.19.3.
