### ISSUE TITLE
Architectury 7.0.63 fails to load and requests currently non-existent fml version 

### ISSUE THREAD

**Issue by liebhaber-von-dunkelheit** [architectury/architectury#363]
From minecraft failed to load error screen:
"Mod File architectury-7.0.63-forge.jar needs language provider javafml:44 or above to load
We have found 43"

Currently highest forge mod loader version accessible through CurseForge launcher is 43.2.0, there is no version 44 or above. (at least according to my launcher) Seems like an insane error, but at least reverting to architectury's 6.4.62 version (2nd most recent release as of posting) 100% resolves the issue and allows me to resume playing my custom modpack.

**Comment by triphora** [comment]
7.x is for 1.19.3.
6.x is for 1.19.2.

**Comment by liebhaber-von-dunkelheit** [comment]
so curseforge updates stuff past the supported version? Well that's kinda batshit and good to know about >w< thank you for the clarification. Seriously doesn't seem right that it'd be able to do that though. That's not like, missing a flag of some kind to let curseforge know to not do that, yea?

**Comment by jclendineng** [comment]
> 7.x is for 1.19.3.
> 6.x is for 1.19.2.

To add to this, it's tagged as 1.19.2 and 1.19.3 in curse...needs the 1.19.2 tag removed, that will resolve this for 1.19.2 users.  Thank you!

**Comment by topia** [comment]
> > 7.x is for 1.19.3.
> > 6.x is for 1.19.2.
> 
> To add to this, it's tagged as 1.19.2 and 1.19.3 in curse...needs the 1.19.2 tag removed, that will resolve this for 1.19.2 users. Thank you!

They already did it.
https://github.com/architectury/architectury-api/issues/364#issuecomment-1344090596
