### ISSUE TITLE
1.19.2 won't start, says: needs language provider javafml:44 or above?

### ISSUE THREAD

**Issue by Jetpack-Cat** [architectury/architectury#364]
![image](https://user-images.githubusercontent.com/100042170/206620950-243bf2c8-3de5-4794-9d8d-e805cb1d0e49.png)

**Comment by BoWeasel** [comment]
Im having this problem as well

**Comment by Juuxel** [comment]
Architectury API 7.x is for 1.19.3, you need to install 6.x.

**Comment by Jetpack-Cat** [comment]
This is the version curseforge installed through the curseforge launcher for 1.19.2

**Comment by Juuxel** [comment]
The curseforge launcher seems to have some sort of a bug. Only 6.x files are tagged as 1.19.2 compatible.
