### ISSUE TITLE
Forge 1.19.3 - Appending items via CreativeTabRegistry "randomizes" the position in the tab

### ISSUE THREAD

**Issue by Lemonszz** [architectury/architectury#365]
Using the **CreativeTabRegistry** to append **RegistrySupplier<Item>** or **Item** ends up up with them in a random position. 
No issues on Fabric. Could be an issue with Forge, but I didn't see any reports on their repo.

Position seems to be random each time.

```
            for(RegistrySupplier<Item> item : ItemHelper.getItems(Constants.MOD_ID))
            {
                CreativeTabRegistry.append(TAB, item);
            }
```

**Forge**
![](https://i.imgur.com/pcb3Tw9.png)

**Fabric**
![](https://i.imgur.com/JXGB0Ay.png)

----
### **Further Tests**
**Directly adding items**
```
            //Directly adding items
            CreativeTabRegistry.append(TAB, BMItems.SCUTTLER_TAIL);
            CreativeTabRegistry.append(TAB, BMItems.CYAN_PETALS);
            CreativeTabRegistry.append(TAB, BMItems.BULBUS_ROOT);
            CreativeTabRegistry.append(TAB, BMItems.COWBOY_HAT);
```
(Still out of order)
![](https://i.imgur.com/znW1XhV.png)

**Vanilla Items**
```
            //Adding Vanilla Items
            CreativeTabRegistry.append(TAB, Items.GLOW_INK_SAC);
            CreativeTabRegistry.append(TAB, Items.INK_SAC);
            CreativeTabRegistry.append(TAB, Items.ACACIA_BOAT);
            CreativeTabRegistry.append(TAB, Items.GREEN_CANDLE);
```
(Also out of order)
![](https://i.imgur.com/3ysNCX3.png)

**Comment by shedaniel** [comment]
Update: If you add items via the builder of the CreativeTab, then its order is retained.
For more information please check https://github.com/MinecraftForge/MinecraftForge/issues/9192

**Comment by shedaniel** [comment]
Looks like they redid the event but they didn't close their issue, so I didn't notice that.
I have updated architectury API to use the new event.
