### ISSUE TITLE
Crashing upon launch

### ISSUE THREAD

**Issue by TheGamingNeko** [architectury/architectury#366]
So, I have been having issues with Minecraft crashing while trying to launch. 
Forge Version: 43.2.0
Architectury version: v6.4.62
Was reading the closed issues and noticed that 7.x is for 1.19.3, which I am not using. I am using 1.19.2, as most of my mods aren't used for 19.3. I don't Its saying that it is a render error, but I don't know what to do.
[crash-2022-11-21_19.22.35-fml.txt](https://github.com/architectury/architectury-api/files/10198090/crash-2022-11-21_19.22.35-fml.txt)

**Comment by triphora** [comment]
> Mod ae2 requires forge 43.1.55 or above, and below 44.0.0
> Currently, forge is 43.1.1

**Comment by TheGamingNeko** [comment]
[crash-2022-12-09_15.04.12-client.txt](https://github.com/architectury/architectury-api/files/10198134/crash-2022-12-09_15.04.12-client.txt)
Uploaded the wrong crash report

**Comment by triphora** [comment]
OptiFine is not supported, post a new crash log if it still occurs w/o OptiFine

**Comment by Juuxel** [comment]
(and that crash still seems to have nothing to do with Architectury)

**Comment by TheGamingNeko** [comment]
Removed optifine, game works as intended. Thank you for the support.
