### ISSUE TITLE
costum modding API

### ISSUE THREAD

**Issue by tigercoding56** [architectury/architectury#367]
seeing as this is a tool to make mods run on both fabric and forge could you add a way to define costum modding API's 
via for example modules   so that for example you could write a module to allow mods for minetest's modding API to run on minecraft or via verse (and of course write a module to allow mods to run on any other modding API / voxel game )  (suggestion,roadmap) ?

**Comment by shedaniel** [comment]
no that’s too far fetched also not reasonable 
we are not trying to be a full abstraction layer
