### ISSUE TITLE
Unable to load Minecraft because of the version.

### ISSUE THREAD

**Issue by Fridge838** [architectury/architectury#371]
Whenever I try to play with fabric, it crashes saying I need to get version 6.2.43 or later. I've uninstalled and re-installed it 4 times, but it all ends up the same. The mods I have (if needed.) are Better animals plus, Fabric API, fabric Langauge kotlin, mob origins, origins, kambrik, bountiful, MCA, owo lib, origins classes, Roughly enough items, terrablender, pehkui, extra origins, medieval origins, too many origins, your in grave danger, wraith waystones, and thats it. Heres the crash report. Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install architectury, version 6.2.43 or later.
Unmet dependency listing:
	 - Mod 'Minecraft Comes Alive' (mca) 7.3.21+1.19.2 requires version 6.2.43 or later of architectury, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by triphora** [comment]
Send a screenshot of your mods folder.

**Comment by Fridge838** [comment]
> Send a screenshot of your mods folder.
![Screen Shot 2022-12-24 at 12 16 10 PM](https://user-images.githubusercontent.com/121332621/209448687-7cf4b034-c714-4f12-b1b6-18d028f09aca.png)

Here, Im on mac by the way, dont know if that changes anything.

**Comment by triphora** [comment]
You downloaded the Forge version when you're using Fabric.
Forge mods do not load on Fabric.

Use https://juuxel.github.io/architectury-api-versions/ to find the version you want.
