### ISSUE TITLE
Game crashes when I use the fabric 1.16.5 version of the mod (With log)

### ISSUE THREAD

**Issue by ShadowBoi74** [architectury/architectury#381]
Sorry about last time 
Here are the logs and crash reports
[latest.log](https://github.com/architectury/architectury-api/files/10531945/latest.log)
[crash-2023-01-30_08.52.09-client.txt](https://github.com/architectury/architectury-api/files/10531946/crash-2023-01-30_08.52.09-client.txt)
Heres the modlist
[modlist.txt](https://github.com/architectury/architectury-api/files/10532031/modlist.txt)
Also I use TLauncher

**Comment by triphora** [comment]
TLauncher is not supported, buy the game and play it legally.
