### ISSUE TITLE
Language doesn't change in fr

### ISSUE THREAD

**Issue by georgio3333** [architectury/architectury#382]
Hello,
I have a problem with the language.
The discussions remain in English while the interface is in the chosen language (French in this case).

Minecraft 1.19.2
Fabric Loader 0.14.12
fabric-api-0.69.0+1.19.2
minecraft-comes-alive-7.4.0+1.19.2-universal
architectury-6.4.62-fabric
![2023-01-31_17 01 55](https://user-images.githubusercontent.com/19244649/215813810-95448784-d3f3-450c-99b8-62fb42fec951.png)

**Comment by Juuxel** [comment]
This is not an issue with Architectury API itself. Whatever mod (MCA?) shows the dialogue doesn't appear to have a French translation. You can direct further comments to the developers of that mod.
