### ISSUE TITLE
Can't start Forge Server with architectury mod added (+log)(1.18.2)

### ISSUE THREAD

**Issue by carlean101** [architectury/architectury#384]
My Forge server works fine, I can launch it with mods and me and my friends can join, but when I add architectury I always get this error (log at bottom) and I'm told to press any key to close the log, my server never starts. I'm playing on Forge 40.2.1 in 1.18.2 and using architectury version 4.10.88, but I've tried downgrading to older versions of the mod and I still get the same/similar error messages. Please help, I really want to make this work so my friends and I can use the friends & foes mod. 

Server log: https://paste.ee/p/YjGnZ#s=0

**Comment by Juuxel** [comment]
Technical explanation ahead:

The issue is with the ASM library used by Forge not being able to read Java 19 code. Not sure where the Java 19 code is coming from exactly though, since Architectury API is built with Java 17.

Can you try using Java 17 to see if that fixes your issue?

**Comment by carlean101** [comment]
> Technical explanation ahead:
> 
> The issue is with the ASM library used by Forge not being able to read Java 19 code. Not sure where the Java 19 code is coming from exactly though, since Architectury API is built with Java 17.
> 
> Can you try using Java 17 to see if that fixes your issue?

Thank you so much, this worked! I had both java 19 and java 17 installed, so uninstalling java 19 fixed it.
