### ISSUE TITLE
not showing up in 1.17.1

### ISSUE THREAD

**Issue by mrdiamondmanguydudeman** [architectury/architectury#387]
I was playing on my 1.17.1 edition and i got an error message about one of my mods causing a crash because of no architectury api, i installed the api into the mods folder and it doesn't show up in the error log, please help.

ERROR LOG: https://pastebin.com/QWrxqhBn

**Comment by triphora** [comment]
Screenshot your mods folder and send it here.

**Comment by mrdiamondmanguydudeman** [comment]
ok
![2023-02-23](https://user-images.githubusercontent.com/118412232/221086585-d759daa2-b36e-480d-a40d-b0151ee395ba.png)

**Comment by mrdiamondmanguydudeman** [comment]
ok here it is 
![Screenshot 2023-02-23 214313](https://user-images.githubusercontent.com/118412232/221086705-057e7c68-adc5-42fd-90b1-458006e3c517.png)

**Comment by triphora** [comment]
Double-check to ensure you have the Fabric version downloaded and not the Forge version.

**Comment by mrdiamondmanguydudeman** [comment]
ok let me check

**Comment by mrdiamondmanguydudeman** [comment]
yea i have the fabric version

**Comment by mrdiamondmanguydudeman** [comment]
i just reinstalled it and it worked
