### ISSUE TITLE
BlockEvent.PLACE is fired after the block has been placed on Fabric, cancellation causes problems

### ISSUE THREAD

**Issue by TropheusJ** [architectury/architectury#398]
The place event is not called until after the block has been placed on Fabric.
It's invoked [here](https://github.com/architectury/architectury-api/blob/1.19.3/fabric/src/main/java/dev/architectury/mixin/fabric/MixinBlockItem.java#L38), in `BlockItem.place`, at the `getClickedPos` call.
This code will only be run if a block is successfully placed.
![image](https://user-images.githubusercontent.com/60247969/229963652-2846bc46-a961-4de3-a222-16e1bad2f9df.png)
This leads to discrepancies. If a mod cancels, an item will not be consumed, even though the block was placed.
An example of this is a Create Deployer in a chunk claimed by FTB Chunks. The deployer tries to place, but FTB Chunks cancels. No item is consumed since it failed. This results in [duplicating blocks](https://github.com/Fabricators-of-Create/Create/issues/876).

**Comment by desht** [comment]
There's actually a PR open for this: https://github.com/architectury/architectury-api/pull/395
