### ISSUE TITLE
Entity Not Realized

### ISSUE THREAD

**Issue by Relaxing9** [architectury/architectury#400]
Related Issue: https://github.com/Faboslav/friends-and-foes/issues/107

### Minecraft version information

Magma version 1.18.2-5c167188 (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge Version 40.2.1)

### Mod loader information

Forge

### Mod loader version information

40.2.1 (Forge)

### Mod version information

4.11.92

#### Error
![image](https://user-images.githubusercontent.com/41935047/235331765-22f8db13-b858-42fd-ac74-da16ccfb6127.png)

#### Logs
https://mclo.gs/TNdquod

**Comment by Relaxing9** [comment]
Updated & issue persists on the latest version of Architectury.

**Comment by topia** [comment]
Magma seems to be a Bukkit-based Minecraft server, but Architectury doesn't support the Bukkit platform, although they provide a Forge interface.

**Comment by Relaxing9** [comment]
No longer relevant to me, so closing this issue.
