### ISSUE TITLE
BlockEvent.PLACE has the wrong BlockState parameter on Fabric.

### ISSUE THREAD

**Issue by Lemonszz** [architectury/architectury#402]
On a Fabric client, the state passed into `BlockEvent.PLACE` is the block that is currently in the position instead of the block that will be placed.

Forge is unaffected.

Tested with Architectury API 8.1.79 for MC 1.19.4

I didn't look into it too much, but I believe it was [caused by this bug fix.](https://github.com/architectury/architectury-api/commit/b8dcba2ee5b2bc6fd4fe600b65058a58f5a2af04).

**Comment by MaxNeedsSnacks** [comment]
Urgh, good catch... That should probably mirror Vanilla and call `getPlacementState(context)` instead
