### ISSUE TITLE
Crash Report>Architectury (architectury)FTB Quests (ftbquests)

### ISSUE THREAD

**Issue by Shadowhisper** [architectury/architectury#415]
Just about to go to the end to fight the wither storm then this error came up and lock me out my session.
[crash-2023-07-02_22.31.36-server.txt](https://github.com/architectury/architectury-api/files/11933466/crash-2023-07-02_22.31.36-server.txt)

**Comment by shedaniel** [comment]
Please report to FTB Quests, this is not caused by architectury.
