### ISSUE TITLE
(Fabric) ClientGuiEvent.INIT_POST doesn't trigger on resize

### ISSUE THREAD

**Issue by Lemonszz** [architectury/architectury#416]
`ClientGuiEvent.INIT_POST` isn't triggering when the screen is resized on Fabric. 

Forge works as expected.

Fabric API also has their own [ScreenEvents](https://github.com/FabricMC/fabric/blob/1.20.1/fabric-screen-api-v1/src/client/java/net/fabricmc/fabric/api/client/screen/v1/ScreenEvents.java) that I don't believe Arch API is using.

**Comment by Matthias1590** [comment]
What version of the api are you using? I recall having the same issue but when testing it with the test mod in the api repo it works just fine

**Comment by Lemonszz** [comment]
The latest, 9.1.10

https://github.com/Lemonszz/SleepRework/blob/1.20/common/src/main/java/party/lemons/sleeprework/client/SleepReworkClient.java#L11

**Comment by Matthias1590** [comment]
@Lemonszz should be fixed now
