### ISSUE TITLE
Game doesn't launch in 1.20.1 [Fabric]

### ISSUE THREAD

**Issue by lbplay29** [architectury/architectury#417]
The game simply doesn't launch:
[crash-2023-07-15_20.24.08-client.txt](https://github.com/architectury/architectury-api/files/12062999/crash-2023-07-15_20.24.08-client.txt)

**Comment by Juuxel** [comment]
Appears to be an issue in the `overloadedarmorbar` mod. Its edits to Minecraft code are loaded during Arch API's initialisation, so that's why the crash log points to it at the top.

```
Mixin [mixins.overloadedarmorbar.json:DrawableHelperMixin from mod overloadedarmorbar] from phase [DEFAULT] in config [mixins.overloadedarmorbar.json] FAILED during APPLY
                                                                   ^^^^^^^^^^^^^^^^^^
```
