### ISSUE TITLE
Allay do not retain nametags

### ISSUE THREAD

**Issue by thatoneiuse** [architectury/architectury#433]
After an Allay is put into a bottle and released, it loses its name.

**Comment by ChiefArug** [comment]
I don't believe that putting Allays into bottles is a vanilla feature, and architectury doesnt add any in game features at all, so this is probably the wrong issue tracker. Try contacting the author of the mod that lets you put Allays in bottles.

**Comment by thatoneiuse** [comment]
Oh. Yeah, that's my bad. I thought this was the tracker for another mod.
