### ISSUE TITLE
Unable to find minecraft worldgen ResourceLocal during registration for worldgen

### ISSUE THREAD

**Issue by baka4n** [architectury/architectury#434]
Caused by: java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root / minecraft:worldgen/configured_feature] does not exist!
![image](https://github.com/architectury/architectury-api/assets/60695447/b3eb1e33-4dd8-431d-8208-df24b48a4fe5)

**Comment by baka4n** [comment]
![image](https://github.com/architectury/architectury-api/assets/60695447/243b4684-3dcf-4bcd-8265-046757179229)
![image](https://github.com/architectury/architectury-api/assets/60695447/f90cd097-635b-402c-8b99-6d1db7dd9aa7)

**Comment by Juuxel** [comment]
Configured features should be registered using data packs, not direct registration in code, as it's a dynamic registry.
