### ISSUE TITLE
I've a strat-up issue with Architectury .. :C issue code : -1 ( FABRIC 1.20.1 )

### ISSUE THREAD

**Issue by KichaneKusuteki** [architectury/architectury#441]
Hiya, i had a problem during the loading of my game today.. What can i do please? :C it's this one : 

[crash-2023-10-05_16.55.02-client.txt](https://github.com/architectury/architectury-api/files/12819907/crash-2023-10-05_16.55.02-client.txt)

Please help me T_T ♥...

**Comment by Juuxel** [comment]
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for waxedicons.mixins.json:GuiGraphicsMixin **from mod waxedicons** during activity

This is not an Architectury API issue, it comes from another mod.

**Comment by KichaneKusuteki** [comment]
Ohhh okii, really thank's ! And thank's again for the fast answer. I've just to delete the mod ' spongepowered ' so ! tyyyy

EDIT : ups no, it was the waxe one, hihi sorry, i've very bad with that stuff, ty again
