### ISSUE TITLE
Entity Renderer Api

### ISSUE THREAD

**Issue by jmendonza** [architectury/architectury#45]
The current architectury api lacks its own alternative to the fabric/forge entity render registry.

Fabric:
> EntityRendererRegistry.INSTANCE.register

Forge:
> RenderingRegistry.registerEntityRenderingHandler

**Comment by YummyLoop** [comment]
Don't know if this helps but this may be used as reference:
Common;
https://github.com/YummyLoop/Yummy/blob/0d8c780208f67613acbb5a04fbe73abeb2c1e578/common/src/main/net/examplemod/registry/EntityAttributeLink.kt
Fabric:
https://github.com/YummyLoop/Yummy/blob/0d8c780208f67613acbb5a04fbe73abeb2c1e578/fabric/src/main/net/examplemod/registry/fabric/EntityAttributeLinkImpl.kt
Forge:
https://github.com/YummyLoop/Yummy/blob/0d8c780208f67613acbb5a04fbe73abeb2c1e578/forge/src/main/net/examplemod/registry/forge/EntityAttributeLinkImpl.kt
