### ISSUE TITLE
ERROR (1)

### ISSUE THREAD

**Issue by LOUCRAFTE** [architectury/architectury#452]
Hi 
I'm trying to install "Identity" in 1.20.1 forge 47.2.5 so i install architectury 9.1.12 forge and i got the error code 1 so i have tried with a more recent version for 1.20.2 and same result....

If somebody got the case I take solution ;-)

(Sry for bad english french issue)

**Comment by Saremix** [comment]
Same issue with me

**Comment by Jab125** [comment]
_Error code 1_ is not a useful error message.
We need logs (`latest.log`, `debug.log`) to diagnose what went wrong.
