### ISSUE TITLE
Crash when registering menus via arch

### ISSUE THREAD

**Issue by gigabit101** [architectury/architectury#453]
Crash when registering menus via arch

Log: https://gist.github.com/gigabit101/51396e0e100a4d6a5c80a66a694112c5

Code: https://github.com/gigabit101/Shrink/blob/1.20.2/dev/common/src/main/java/net/gigabit101/shrink/init/ModContainers.java

architectury_version=10.0.15

fabric_loader_version=0.14.22
fabric_api_version=0.89.0+1.20.2

forge_version=48.0.38
neoforge_version=20.2.59-beta

If I am just being stupid please do let me know.

**Comment by gigabit101** [comment]
Looking at the Neo source this has been renamed to IMenuTypeExtension

https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/neoforged/neoforge/common/extensions/IMenuTypeExtension.java

**Comment by Juuxel** [comment]
https://github.com/architectury/architectury-api/blob/9aba3cf1dccf43a0b000413c7544196bfb643e25/forge/src/main/java/dev/architectury/registry/menu/forge/MenuRegistryImpl.java#L35

Yep, `IForgeMenuType` needs that as a platform mapping for Neo.

**Comment by gigabit101** [comment]
Yep, Just not figured out how yet or I would have submitted a PR lol
