### ISSUE TITLE
1.20.1 Server Crash

### ISSUE THREAD

**Issue by MokahTGS** [architectury/architectury#482]
Getting a crash loading our server.

Minecraft 1.20.1
Forge: forge-1.20.1-47.2.17
Architectury: architectury-9.2.14-forge

Crash Log: https://pastebin.com/yGsi4Wdf

**Comment by shedaniel** [comment]
Seems to be caused by mcpitanlib as it didnt register their eventbus

**Comment by Jab125** [comment]
> Seems to be caused by mcpitanlib as it didnt register their eventbus

This appears to been an issue in a mod that uses Architectury API.
