### ISSUE TITLE
Minecraft doesent launch on newest version

### ISSUE THREAD

**Issue by sirben99** [architectury/architectury#49]
Hey!

I cant launch the game with the newest version of Architecture API.

MC version: 1.16.5
Forge version: 36.0.40
Mod version: 1.8.124
Other mods: No
Launcher: MultiMc

Latest.log:
[latest.log](https://github.com/architectury/architectury-api/files/6045367/latest.log)

**Comment by shedaniel** [comment]
Fixed in 60cc189
