### ISSUE TITLE
Mod crashes on new NeoForge 1.20.6 builds

### ISSUE THREAD

**Issue by ModernGamingWorld** [architectury/architectury#508]
![2024-05-25_20 11 24](https://github.com/architectury/architectury-api/assets/75923060/07eaec5a-ea67-4951-b246-0ae9fb17cca0)

**Comment by SerLizar** [comment]
This affects NeoForge 20.6.78+ which made change to how events are handled.

**Comment by RoyalTwo** [comment]
For reference, I have the same problem but the given error is for FillBucketEvent.
![image](https://github.com/architectury/architectury-api/assets/20693460/d0c86301-7388-43dc-8399-d24730c3cedf)

**Comment by Dianliang233** [comment]
related to https://github.com/neoforged/NeoForge/pull/588
