### ISSUE TITLE
[Feature] Add `getEntries()` method to `DeferredRegister`

### ISSUE THREAD

**Issue by moritz-htk** [architectury/architectury#510]
I propose adding a `getEntries()` method to the `DeferredRegister` class. This method would allow retrieving all entries from the `DeferredRegister` at once instead of calling each one individually.

Add the following method to the `DeferredRegister` class:
```java
    public Collection<RegistrySupplier<T>> getEntries() {
        return entryView;
    }
```

With this method, it would be possible to streamline operations in datagen, for example:
```java
    @Override
    protected void registerModels() {
        MFItems.ITEMS.getEntries().stream().map(RegistrySupplier::get).forEach(this::basicItem);
    }
```

Without this method, each entry must be written individually, as shown here:
```java
    @Override
    protected void registerModels() {
        basicItem(...)
        basicItem(...)
        basicItem(...)
        basicItem(...)
        basicItem(...)
    }
```

I have tested this implementation and it works as intended.

**Comment by shedaniel** [comment]
it extends Iterable already, you can just for loop it, for example:
```java
for (RegistrySupper<Item> item : MFItems.ITEMS) {
    basicItem(item);
}
```
