### ISSUE TITLE
1.21 neoforge mod fails to load

### ISSUE THREAD

**Issue by Jayv6** [architectury/architectury#522]
versions
Neoforge 1.21 (21.0.32 beta)
Architectury 13.0.1
https://mclo.gs/xCRzSnS (log)
I cannot get the game to load with just this mod

**Comment by ffuentesm** [comment]
![image](https://github.com/architectury/architectury-api/assets/44974827/f396cc3a-68c8-475e-91cc-c3a87195e678)

New Neoforge 21.0.31 made the following changes to damage events:
```
import net.neoforged.neoforge.event.entity.living.LivingHurtEvent; 
``` 

```
import net.neoforged.neoforge.event.entity.living.LivingIncomingDamageEvent; 
```

``` 
public static void dodge(LivingHurtEvent event) { 
``` 

``` 
public static void dodge(LivingIncomingDamageEvent event) {
```

```
public static void livingDamageEvent(LivingDamageEvent event) {
        if (!(event.getSource().getEntity() instanceof Player player)) 
```
 
```        
public static void livingDamageEvent(LivingIncomingDamageEvent event) {
        if (!(event.getEntity() instanceof Player player))
```

**Comment by CsillaAria** [comment]
Having the same problem.

**Comment by Logan9312** [comment]
Same problem here. It happened after I had to update my neoforge past `21.0.31-beta` I believe

**Comment by Steinzu** [comment]
Same here, the error only happens on neoforge `21.0.31-beta` and forward

**Comment by EstebanLoupias** [comment]
Having exactly the same problem!

**Comment by ashton727** [comment]
Can confirm this issue on my machine.

**Comment by Fidulus** [comment]
I´m on version 21.0.37 and architectury crashes the game, without it ofc none of the dependent mods are usable. my crashlog looks something like this:

-- Head --
Thread: Render thread
Stacktrace:
	at TRANSFORMER/architectury@13.0.2/dev.architectury.platform.hooks.EventBusesHooks.lambda$whenAvailable$0(EventBusesHooks.java:34) ~[architectury-13.0.2-neoforge.jar%23330!/:?] {re:classloading}
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
	at TRANSFORMER/architectury@13.0.2/dev.architectury.platform.hooks.EventBusesHooks.whenAvailable(EventBusesHooks.java:34)

**Comment by Shadowglitchjpg** [comment]
I have a similar problem, the game says that architectury is not available
