### ISSUE TITLE
Neoforge 21.0.40+ compatability issue

### ISSUE THREAD

**Issue by Kevin-Marsh** [architectury/architectury#529]
ToolActions were renamed to ItemAbilities in Neoforge 21.0.40-beta. This prevents architectury from functioning on 40+ versions.

**Comment by jelly612** [comment]
Has this been fixed yet. Sorry if i am being a bother.

**Comment by forkiesassds** [comment]
> Has this been fixed yet. Sorry if i am being a bother.

Yes... However this issue wasn't closed.

**Comment by jelly612** [comment]
I'm just worried since i still can't play.

**Comment by forkiesassds** [comment]
> I'm just worried since i still can't play.

Update to Architectury API 13.0.3. If other mods are crashing update them and if that still doesn't work then wait for them to update.

**Comment by jelly612** [comment]
Alright thank you.

**Comment by jelly612** [comment]
Oh and i've tried updating to Architectury API 13.0.3.
And it hasn't worked so i hope that they do update it.
