### ISSUE TITLE
Failed to load Architectury

### ISSUE THREAD

**Issue by Maltshakes** [architectury/architectury#53]
Got an error and crash while trying to launch Minecraft. 

https://i.imgur.com/yrqg6U9.png

https://pastebin.com/Arr8HdEK

**Comment by MaxNeedsSnacks** [comment]
This *should* longer be an issue with the newest Architectury API version?

**Comment by MaxNeedsSnacks** [comment]
Can you check whether this is still an issue for you with the latest Architectury API version?

**Comment by Maltshakes** [comment]
I've not seen it happen again with the update, thank you.
