### ISSUE TITLE
architectury-13.0.3-neoforge.jar causing game to crash when trying to open the crative inventory

### ISSUE THREAD

**Issue by CsillaAria** [architectury/architectury#538]
I'm on NeoForge 21.0.78, but the issue started before that. Everything works fine in survival but trying to open the inventory in creative mode causes the game to crash. 

Exit Code: -1 message:  The game crashed whilst unexpected error Error: net.neoforged.fml.ModLoadingException: Loading errors encountered:

Crash Report: https://bytebin.lucko.me/ULsHK3DSvJ

**Comment by Kevin-Marsh** [comment]
I also have this issue. Neoforge had a breaking change that effect Architectury. I do not know if that is related though. 
SpawnPlacementRegisterEvent renamed to RegisterSpawnPlacementsEvent

BuildCreativeModeTabContentsEvent was also messed with here: https://github.com/neoforged/NeoForge/commit/2a8d908aea066c923ccd52552583d331d9725cf4

Crash Report: https://mclo.gs/0vCZG0Q

**Comment by Jab125** [comment]
See #539

**Comment by Kevin-Marsh** [comment]
Ahh. You are awesome. Thank you.
