### ISSUE TITLE
can´t load my world anymore (singleplayer) after updating to neoforge 21.0.80 

### ISSUE THREAD

**Issue by Fidulus** [architectury/architectury#540]
After updating my mods and neoforge to version 21.0.80 i can´t enter my "singleplayer" world anymore.
It crashes with "connection Lost - Network Protocol Error"

![image](https://github.com/architectury/architectury-api/assets/48780170/14e8484b-9bec-4ebd-a42d-b1881150f061)

My debug file looks like this.
https://pastebin.com/1nshyxiz

If the crash is related to something else that i am not aware of, please be so kind to point me at it as i am not a pro in reading those files. 
Thank you

**Comment by Jab125** [comment]
It should've been fixed in #539, closing.
