### ISSUE TITLE
Minecraft launcher crash - new crash file - Version 21.0.86

### ISSUE THREAD

**Issue by Fidulus** [architectury/architectury#541]
https://pastebin.com/BtwY5fbk

After updating everything to newest version game won´t start anymore.
I hope my crash log helps locating any problems.
It seems to me this is still an architectury issue.
If that is not the case please tell me whats wrong instead, i´m not very good in reading the crash logs.
Thank you

**Comment by TheeMrCheeky** [comment]
Ya I am having this issue with neoforge 
[crash-2024-07-12_07.10.01-client.txt](https://github.com/user-attachments/files/16192836/crash-2024-07-12_07.10.01-client.txt)

**Comment by Jab125** [comment]
Duplicate of #527
