### ISSUE TITLE
"Architectury is not available" with the latest mod version

### ISSUE THREAD

**Issue by Shadowglitchjpg** [architectury/architectury#542]
NeoForge version: 21.0.86
Mod version: 13.0.4
When I try to launch the game with the latest version of the mod, it crashes.
![AAAAAAAAAA](https://github.com/user-attachments/assets/4c1988aa-cdb9-4dd8-a22b-5012d1a5c9d8)

**Comment by Jab125** [comment]
We need logs to provide support, open a new issue with the logs attached.

**Comment by Jab125** [comment]
You could see if it is related to #528
