### ISSUE TITLE
NeoForge crash at startup with Java 22

### ISSUE THREAD

**Issue by mben42** [architectury/architectury#549]
Hi,

I get a crash at startup with NeoForge in 1.21.1 https://paste.ee/p/VyTBT

I tested both NeoForge versions 21.1.15 and 21.1.16.

**Comment by Sheffy55** [comment]
> Hi,
> 
> I get a crash at startup with NeoForge in 1.21.1 https://paste.ee/p/VyTBT
> 
> I tested both NeoForge versions 21.1.15 and 21.1.16.

I was getting this too, the cause is Java type, needs to be Java 21, Java 22 breaks the mod for some reason. Needs am update to add support for Java 22

**Comment by mben42** [comment]
> > Hi,
> > I get a crash at startup with NeoForge in 1.21.1 https://paste.ee/p/VyTBT
> > I tested both NeoForge versions 21.1.15 and 21.1.16.
> 
> I was getting this too, the cause is Java type, needs to be Java 21, Java 22 breaks the mod for some reason. Needs am update to add support for Java 22

Thanks, I can confirm it works with Java 21.

**Comment by ThexXTURBOXx** [comment]
Most likely not related to Architectury API - the problem is on NeoForged's side.
It uses ASM 9.5, which does not support Java 22. For that, newer ASM versions are needed.

**Comment by mben42** [comment]
> Most likely not related to Architectury API - the problem is on NeoForged's side. It uses ASM 9.5, which does not support Java 22. For that, newer ASM versions are needed.

NeoForge starts without Architectury, I suppose it's when it tries to load the mod that the crash happens.

Thanks for your answer, I close the issue then.
