### ISSUE TITLE
Blocks not dropping anything, persists until server restart

### ISSUE THREAD

**Issue by NielsPilgaard** [architectury/architectury#56]
Hey o/ I have an issue that has Arch in the stacktrace. It's probably not caused by Arch, but I was thinking you might be able to see who I should actually report this to?

The issue:
> Around 1 or 2 AM last night after being up for a few hours, all dropped items started disappearing instantly. I'm not sure what caused the bug, but it persisted until server restart.

> The latest.log was unavailable, so all I have is this chunk of the logs.
https://pastebin.com/wamTGS9W

Relayed from https://github.com/NillerMedDild/Enigmatica6/issues/1510

**Comment by shedaniel** [comment]
Please report to simple farming

**Comment by NielsPilgaard** [comment]
Thanks!
