### ISSUE TITLE
[1.21] Architectury 13.0.8 is labelled as incompatible with 1.21.1 on Modrinth

### ISSUE THREAD

**Issue by cassiancc** [architectury/architectury#575]
Architectury 13.0.8 is not labelled as compatible with 1.21.1, unlike 13.0.6. This causes some mods like Right Click Harvest that depend on 13.0.8 to crash when loaded with 13.0.6, despite that currently being the latest version that supports 1.21.1.

**Comment by shedaniel** [comment]
Thanks for reporting, this is now resolved
