### ISSUE TITLE
Abnormal Mod conflict with Loading Timer

### ISSUE THREAD

**Issue by Blobanium** [architectury/architectury#58]
Extended from [Loading Timer #10](https://github.com/Blobanium/Loading-Timer/issues/10)

All the details should be in that issue i mentioned above.

if theres anything else make sure you tell me, thanks.

**Comment by shedaniel** [comment]
Please produce a log with a custom log4j config file to display the class name of the stdout.

**Comment by Blobanium** [comment]
ok will do, just need to know how to do that as im very new into java and making mods for fabric. Suspect its something to do with apache log4j, right?

**Comment by shedaniel** [comment]
I'm sorry but I do want to point out that your mod is fundamentally flawed (well after a quick glance, correct me if I am wrong), you seems to be checking TitleScreen#init to determine when the game _starts to load_ and _finished loading_, init is called constantly throughout the game, during window resize and more, consider starting the timer when Fabric Loader starts, and ending the timer on the first TitleScreen#init.

**Comment by Blobanium** [comment]
ok i will, was thinking about changing that with something else, because i knew using that method is a bad idea, but the only problem trying to correct that was that i didn't really know what to replace it with. I'll probably try your suggestion if i probably can.

**Comment by Blobanium** [comment]
ok closing this issue as this is most likely fixed over on my end
