### ISSUE TITLE
cannot create project

### ISSUE THREAD

**Issue by WillTheCodeWork** [architectury/architectury#582]
I am unable to create a project, as when I extract the generated zip file from the [Architectury Template Generator](https://generate.architectury.dev/), it crashes as soon as I run the gradlew batch file. I am on windows, the error that I get is in the common\build.gradle file saying that the line two `common rootProject.enabled_platforms.split(',')` doesn't work. The specific error it gives is: `No modloader with id`. I am on Architect Plugin version 3.4.159 and Architectury Loom version 1.6.411, with minecraft version 1.21. I did choose yarn as the mappings, I didn't edit any of the code post-extraction of the zip. Any help would be appreciated.

**Comment by cassiancc** [comment]
Did you check any of the boxes for Neoforge or Fabric? That error sounds like you didn't enable any mod loaders, so it's trying to build without any enabled.

**Comment by WillTheCodeWork** [comment]
I didn't, I will try that, thank you for your help!

**Comment by WillTheCodeWork** [comment]
Thank you! That worked
