### ISSUE TITLE
[1.16.5] Crash on world-join

### ISSUE THREAD

**Issue by NielsPilgaard** [architectury/architectury#59]
Edit: I should've checked if there was an update before posting this, checking if it resolves my issue now.

I think I have a crash that's actually from Architectury for once 😄 

Crash: https://gist.github.com/NillerMedDild/733cfae72152a9ac8e70bf4a4f9af2ec

### Versions
- Forge-1.16.5-36.0.46
- architectury-1.8.130-forge

**Comment by MaxNeedsSnacks** [comment]
Can you run this with Java 14 and enhanced NPEs? That exception doesn't make much sense to me unfortunately

**Comment by NielsPilgaard** [comment]
Don't mind me, updating fixed it ^^'

**Comment by MaxNeedsSnacks** [comment]
Oh nice! If it does happen again, feel free to reopen ^^
