### ISSUE TITLE
Slight Gui Modifications, Potentially Architectury 

### ISSUE THREAD

**Issue by jbjornberg** [architectury/architectury#63]
Conflict with Enhancement https://www.curseforge.com/minecraft/mc-mods/enhancement-fabric

Adding this mod causes an issue for me where when I equip any armor piece, it causes the inventory UI to jump up to the top left of my screen and my inventory gets bugged.  Unequipping the armor piece fixes the inventory UI, but all entities (including other players) then fail to render and it goes into a corrupt state. Sometimes, I also am no longer able to see my character as well. I have to restart to fix it, but it breaks as soon as I equip any armor again.  I'm on 1.16.5

The error logs aren't very helpful though... https://gist.github.com/spoorn/eab71916e5b98265a3b3170c14e50800

**Comment by shedaniel** [comment]
Please try to reproduce the issue with only architectury.

**Comment by shedaniel** [comment]
No answer, please report again if you have more info
