### ISSUE TITLE
Inventory crashes

### ISSUE THREAD

**Issue by srnyx** [architectury/architectury#65]
**Log 1:** https://pastebin.com/npFwQZ4S
**Log 2:** https://pastebin.com/GF4kGwBt

**Original issue (opened on wrong repository):** https://github.com/comp500/Indium/issues/40

**Comment by srnyx** [comment]
Please fix this soon I crash literally every time I do anything that involves moving items
😩 [Rejoin spam](https://user-images.githubusercontent.com/25808801/112381068-8bae5680-8cc0-11eb-91ec-e9b0129e779d.png)

**Comment by shedaniel** [comment]
Can you attach a crash with this mod to give more info?
https://www.curseforge.com/minecraft/mc-mods/mixintrace

**Comment by srnyx** [comment]
> Can you attach a crash with this mod to give more info?
> https://www.curseforge.com/minecraft/mc-mods/mixintrace

https://pastebin.com/iKWTsvFy

**Comment by srnyx** [comment]
I think it has something to do with Inventory Control Tweaks, https://gitlab.com/supersaiyansubtlety/inventory_control_tweaks/-/issues/5

Yep, confirmed it's ICT's latest update (disabled the mod and it's no longer happening)
