### ISSUE TITLE
Crash with Quark (I Think)

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [architectury/architectury#68]
Log: [https://paste.ee/p/vBzL9](https://paste.ee/p/vBzL9)

**Comment by MaxNeedsSnacks** [comment]
Hmm, why do you think Architectury is the mod that crashes here? The only reference I can find is to our GameRulesAccessor mixin,  which shouldn't crash unless you use another mod that messes with the structure of GameRules (since this is only an invoker that gives us access to the "create" method)

**Comment by BeansBeefBroccoli** [comment]
I think it's a Mixin incompatibility with Architectury and Quark, but I don't know, because I haven't had this problem before, and the game loads, (which I don't think happens normally) and it crashes when I click "Singleplayer." Maybe I missed something in the logs, but I skimmed through the error multiple times and didn't see any other mods mentioned.

**Comment by BeansBeefBroccoli** [comment]
I ran into this in another pack and it is not Architectury, sorry.
