### ISSUE TITLE
Villager Trade Event

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [architectury/architectury#70]
Should be relatively trivial to implement, even if a corresponding event doesn't seem(?) to exist on the fabric side.

That said, we should probably also look into utility functions to make adding Villager trades easier than the vanilla way, which is of course, janky as all hell once again.

**Comment by DaddyP1G** [comment]
FYI- There is a new mod that does this.  https://www.curseforge.com/minecraft/mc-mods/custom-villager-trades
