### ISSUE TITLE
File upload for 2.0.141 marked incorrectly on CurseForge

### ISSUE THREAD

**Issue by srnyx** [architectury/architectury#71]
[[Fabric 21w14a] v2.0.141](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric/files/3270386) is marked as compatible with 1.16-Snapshot, 1.16.4, and 1.16.5, but it was built for 21w14a.

**Comment by shedaniel** [comment]
Sorry for that, this has been sorted, thanks!
