### ISSUE TITLE
Incompatibility with Cardboard, Entrypoint Error?

### ISSUE THREAD

**Issue by jbjornberg** [architectury/architectury#77]
https://pastebin.com/pJ36sEcn
To replicate the issue, install [Cardboard](https://www.curseforge.com/minecraft/mc-mods/cardboard) & [Architectury API (Fabric)](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric) along with the necessities needed to run Fabric.

**Comment by MaxNeedsSnacks** [comment]
Cardboard completely overwrites many methods in `net.minecraft.server` to replicate Bukkit's patches, which makes it fundamentally incompatible with **a lot** of server-side mods. This is unfortunately not something we can fix.

**Comment by jbjornberg** [comment]
> Cardboard completely overwrites many methods in `net.minecraft.server` to replicate Bukkit's patches, which makes it fundamentally incompatible with **a lot** of server-side mods. This is unfortunately not something we can fix.

This is the only incompatibility I have in my 200+ mod pack so far.. If I remove Architectury, the pack runs fine. I understand that this means the dependencies are likely incompatible as well, but I'm not using your library for server-side mods. Are you sure there's no quick fix I could do for this or is it really a hefty overhaul that would be needed for this functionality?

**Comment by shedaniel** [comment]
architectury is not at fault here, you should contact support over at cardboard.

**Comment by jbjornberg** [comment]
I posted this issue in both GitHubs, they just seem to be drowning in problems right now. I don't believe that this is Architectury's fault at all. I'm just verifying that it isn't a simple fix. Do you think it would be a lot of work to make these mods compatible, or would it be a pretty simple fix on Cardboard's end?

**Comment by shedaniel** [comment]
No, Cardboard completely replaces the pieces of code that we are trying to inject into, we have no way to fix this on our side.

The main reason why they have their issues piles up is because they just go around replacing things, breaking lots of mods.

**Comment by jbjornberg** [comment]
I see, thank you for the clarification. Hopefully they can do something on their end.
