### ISSUE TITLE
Hay can I use your mod for a mod pack that I am making for me and my friends server because publishing it is the only way to use mods on servers 

### ISSUE THREAD

**Issue by PJmax2005** [architectury/architectury#79]
Hay can I use your mod for a mod pack that I am making for me and my friends server because publishing it is the only way to use mods on servers

**Comment by MaxNeedsSnacks** [comment]
You sure can! As a quick side note, ***all*** mods uploaded to CurseForge can **always** be used in CurseForge packs, and unless you are planning to reupload only the mod itself to some offshoot site where we can't control what happens with it at all, we're generally fine with it being used elsewhere, as well!
