### ISSUE TITLE
Kotlin Usage

### ISSUE THREAD

**Issue by PssbleTrngle** [architectury/architectury#8]
Is it possible to use this with Kotlin using the [Kotlin for Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge) / [Fabric Language Kotlin](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin) in the respective `build.gradle` file?

**Comment by shedaniel** [comment]
It should be possible, talk to us in the discord if you have any issues.

**Comment by PssbleTrngle** [comment]
I'll try it out and report back
