### ISSUE TITLE
No archives uploaded to Modrinth

### ISSUE THREAD

**Issue by triphora** [architectury/architectury#80]
You've had a [Modrinth page](https://modrinth.com/mod/lhGA9TYQ) for 5 months and yet there are no archives uploaded to it. :confused:
Also - the license there is listed as `CUSTOM` when it should be `LGPL-3.0`

**Comment by shedaniel** [comment]
Just fixed the license, but there are currently no plans to publish to modrinth, it is just too annoying right now.

**Comment by Username404-59** [comment]
I agree, and https://github.com/modrinth/minotaur/issues/6 will be annoying for architectury projects; uploading the fabric version of a mod and then the forge version as an additional file would result in the second file being the main one for some reason

**Comment by triphora** [comment]
This is resolved now ;)
