### ISSUE TITLE
Target: Native

### ISSUE THREAD

**Issue by shedaniel** [architectury/architectury#9]
Targets native vanilla Minecraft built on top of mojmap, and creates a jar mod installer (or maybe just ask people to delete META-INF and replace the raw files?)

A static asm transformer and mixin applicator (possibly?)

Use Case: None LMAO, well could be used to mod combat snapshots (fabric still doesn't support these) or get ahead of fabric itself (I am speed!)

**Comment by MaxNeedsSnacks** [comment]
I'm assuming we are no longer pursuing this? Doesn't exactly seem like a goall we're gonna go after anytime soon :p
