### ISSUE TITLE
Architectury v1.15.12 Forge stops Light Overlay from Loading

### ISSUE THREAD

**Issue by papaworld** [architectury/architectury#90]
MC: 1.16.5
FML: 36.1.4
Light Overlay: 5.8.0
Architectury: [Forge 1.16.4/5] v1.15.12

The CrashLog points to Architectury. Version 1.14.157 works fine.

[crash-2021-05-20_11.55.57-fml.txt](https://github.com/architectury/architectury-api/files/6517722/crash-2021-05-20_11.55.57-fml.txt)

Thank You

**Comment by ghost** [comment]
Yeah, same with FML 36.1.0 and Light Overlay 5.8.1.

**Comment by MaxNeedsSnacks** [comment]
Architectury Plugin 3.2 broke things, it seems.

We'll downgrade to 3.1 until that's a bit more stable. (see f6e86f7)

**Comment by papaworld** [comment]
Thank you for your response and attention. Very kewl!!!
