### ISSUE TITLE
[Request] Particle Factory Registration API

### ISSUE THREAD

**Issue by Leo40Git** [architectury/architectury#93]
An API to register particle factories on the client. Necessary for any mod that wants to even approach custom particles.

**Forge:** [`ParticleFactoryRegisterEvent`](https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/client/event/ParticleFactoryRegisterEvent.java) (Forge makes `ParticleManager.registerFactory` accessible)
**Fabric:** [`ParticleFactoryRegistry`](https://github.com/FabricMC/fabric/blob/1.16/fabric-particles-v1/src/main/java/net/fabricmc/fabric/api/client/particle/v1/ParticleFactoryRegistry.java)

~~Additionally, a utility class similar to [`FabricParticleTypes`](https://github.com/FabricMC/fabric/blob/1.16/fabric-particles-v1/src/main/java/net/fabricmc/fabric/api/particle/v1/FabricParticleTypes.java) would be appreciated, just so we don't need to extend `DefaultParticleType`.~~ nvm, seems like it's pretty much useless

**Comment by MaxNeedsSnacks** [comment]
Weird, this should've been closed by #110. Anyways, yeah it's a thing now!
